// Bible people used by Guess Who, Who Am I?, Fact or Fiction, Odd One Out, etc.
// tags (space separated) power the Guess Who yes/no questions — see GUESS_WHO_QUESTIONS.
// clues are ordered from hardest to easiest and written in the first person.

export const PEOPLE = [
  // ── Old Testament ──────────────────────────────────────────────
  { id: 'adam', name: 'Adam', e: '🍎', title: 'First man', t: 'OT', g: 'm', tags: 'genesis',
    clues: ['I lived 930 years.', 'I gave names to every animal.', 'I was formed from the dust of the ground.', 'My wife and I ate the forbidden fruit in Eden.'] },
  { id: 'eve', name: 'Eve', e: '🐍', title: 'Mother of all living', t: 'OT', g: 'f', tags: 'genesis',
    clues: ['My name means "living".', 'I had sons named Cain, Abel and Seth.', 'I was made from a rib.', 'A serpent tricked me in the garden.'] },
  { id: 'cain', name: 'Cain', e: '🌾', title: 'Farmer', t: 'OT', g: 'm', tags: 'genesis',
    clues: ['I built a city and named it after my son Enoch.', 'God put a mark on me for protection.', 'I asked, "Am I my brother\'s keeper?"', 'I killed my brother Abel.'] },
  { id: 'abel', name: 'Abel', e: '🐑', title: 'Keeper of sheep', t: 'OT', g: 'm', tags: 'genesis shepherd',
    clues: ['Hebrews 11 says I still speak, though dead.', 'I offered the firstborn of my flock.', 'God accepted my offering.', 'My older brother Cain killed me.'] },
  { id: 'methuselah', name: 'Methuselah', e: '⏳', title: 'Oldest man', t: 'OT', g: 'm', tags: 'genesis',
    clues: ['My father Enoch walked with God.', 'My grandson built a very big boat.', 'I lived 969 years.', 'I am the oldest person recorded in the Bible.'] },
  { id: 'noah', name: 'Noah', e: '🚢', title: 'Ark builder', t: 'OT', g: 'm', tags: 'genesis water',
    clues: ['I planted a vineyard after a great disaster.', 'My sons were Shem, Ham and Japheth.', 'I sent out a raven and a dove.', 'I built an ark before the flood.'] },
  { id: 'abraham', name: 'Abraham', e: '⭐', title: 'Father of many nations', t: 'OT', g: 'm', tags: 'genesis renamed egypt angel shepherd',
    clues: ['I paid a tithe to Melchizedek.', 'I left Ur of the Chaldeans.', 'God said my descendants would be like the stars.', 'I nearly sacrificed my son Isaac on Mount Moriah.'] },
  { id: 'sarah', name: 'Sarah', e: '😂', title: 'Mother of Isaac', t: 'OT', g: 'f', tags: 'genesis renamed egypt angel',
    clues: ['I was buried in the cave of Machpelah.', 'My name used to be Sarai.', 'I laughed when I heard I would have a son.', 'I gave birth to Isaac at ninety years old.'] },
  { id: 'hagar', name: 'Hagar', e: '🏜️', title: 'Egyptian servant', t: 'OT', g: 'f', tags: 'genesis foreign angel egypt water',
    clues: ['I called God "the God who sees me".', 'An angel found me by a spring in the wilderness.', 'I was Sarah\'s Egyptian servant.', 'I am the mother of Ishmael.'] },
  { id: 'isaac', name: 'Isaac', e: '🪵', title: 'Son of promise', t: 'OT', g: 'm', tags: 'genesis water',
    clues: ['I reopened the wells my father had dug.', 'My name means "he laughs".', 'I blessed Jacob, thinking he was Esau.', 'I carried the wood up Mount Moriah.'] },
  { id: 'rebekah', name: 'Rebekah', e: '🐪', title: 'Wife of Isaac', t: 'OT', g: 'f', tags: 'genesis water',
    clues: ['My brother was Laban.', 'I helped my younger son trick his father.', 'I was the mother of twins, Esau and Jacob.', 'I watered the camels of Abraham\'s servant at a well.'] },
  { id: 'jacob', name: 'Jacob', e: '🪜', title: 'Israel', t: 'OT', g: 'm', tags: 'genesis renamed dream shepherd egypt water',
    clues: ['I worked 14 years to marry the woman I loved.', 'I wrestled with God and got a new name.', 'I dreamed of a ladder reaching to heaven.', 'I was the father of twelve sons.'] },
  { id: 'esau', name: 'Esau', e: '🍲', title: 'Hunter', t: 'OT', g: 'm', tags: 'genesis',
    clues: ['I became the father of the Edomites.', 'I was a skilful hunter.', 'I was the hairy twin.', 'I sold my birthright for a bowl of stew.'] },
  { id: 'rachel', name: 'Rachel', e: '💧', title: 'Beloved wife of Jacob', t: 'OT', g: 'f', tags: 'genesis shepherd water',
    clues: ['I hid my father\'s household idols under a camel saddle.', 'I died on the way to Bethlehem.', 'Jacob met me at a well while I tended sheep.', 'I am the mother of Joseph and Benjamin.'] },
  { id: 'leah', name: 'Leah', e: '👀', title: 'First wife of Jacob', t: 'OT', g: 'f', tags: 'genesis',
    clues: ['The Bible says I had weak or tender eyes.', 'I was married to Jacob through my father\'s trick.', 'My younger sister was Rachel.', 'I was the mother of Judah and Levi.'] },
  { id: 'joseph_ot', name: 'Joseph', e: '🧥', title: 'Dreamer', t: 'OT', g: 'm', tags: 'genesis dream egypt prison shepherd',
    clues: ['I married Asenath and named my sons Manasseh and Ephraim.', 'I was sold by my brothers for twenty pieces of silver.', 'I interpreted Pharaoh\'s dreams about cows and grain.', 'My father gave me a special coat.'] },
  { id: 'moses', name: 'Moses', e: '🔥', title: 'Lawgiver', t: 'OT', g: 'm', tags: 'prophet author egypt water shepherd miracle angel',
    clues: ['I married Zipporah, a Midianite.', 'I was hidden in a basket among the reeds of the Nile.', 'God spoke to me from a burning bush.', 'I brought the Ten Commandments down from Mount Sinai.'] },
  { id: 'aaron', name: 'Aaron', e: '🌿', title: 'First high priest', t: 'OT', g: 'm', tags: 'priest egypt miracle',
    clues: ['My staff budded, blossomed and produced almonds.', 'I made a golden calf while my brother was on the mountain.', 'I spoke to Pharaoh on my brother\'s behalf.', 'I was Israel\'s first high priest.'] },
  { id: 'miriam', name: 'Miriam', e: '🥁', title: 'Prophetess', t: 'OT', g: 'f', tags: 'prophet egypt water',
    clues: ['I was struck with leprosy for seven days.', 'I led the women with a tambourine after the Red Sea crossing.', 'I watched over my baby brother in the reeds.', 'I was the sister of Moses and Aaron.'] },
  { id: 'joshua', name: 'Joshua', e: '🎺', title: 'Conqueror', t: 'OT', g: 'm', tags: 'warrior author bookname renamed egypt water miracle angel',
    clues: ['My name was once Hoshea.', 'I was one of the twelve spies sent into Canaan.', 'I prayed and the sun stood still.', 'The walls of Jericho fell when we marched and shouted.'] },
  { id: 'caleb', name: 'Caleb', e: '⛰️', title: 'Faithful spy', t: 'OT', g: 'm', tags: 'warrior egypt',
    clues: ['I gave my daughter Achsah to the man who captured Kiriath-sepher.', 'At 85 I said, "Give me this mountain."', 'I inherited Hebron.', 'I was one of only two spies who trusted God.'] },
  { id: 'rahab', name: 'Rahab', e: '🧶', title: 'Woman of Jericho', t: 'OT', g: 'f', tags: 'foreign',
    clues: ['I am named in the genealogy of Jesus in Matthew.', 'My house was built into the city wall.', 'I tied a scarlet cord in my window.', 'I hid two Israelite spies in Jericho.'] },
  { id: 'deborah', name: 'Deborah', e: '🌴', title: 'Judge of Israel', t: 'OT', g: 'f', tags: 'prophet warrior',
    clues: ['I sang a victory song after Sisera was defeated.', 'I told Barak to go to battle.', 'I held court under a palm tree.', 'I was the only female judge of Israel.'] },
  { id: 'gideon', name: 'Gideon', e: '🧥', title: 'Mighty warrior', t: 'OT', g: 'm', tags: 'warrior angel renamed',
    clues: ['I was also called Jerub-baal.', 'An angel found me threshing wheat in a winepress.', 'I tested God with a fleece.', 'I defeated the Midianites with only 300 men.'] },
  { id: 'samson', name: 'Samson', e: '💪', title: 'Strongman', t: 'OT', g: 'm', tags: 'warrior prison',
    clues: ['I posed a riddle about honey and a lion.', 'I carried away the gates of Gaza.', 'My strength was in my uncut hair.', 'Delilah betrayed me to the Philistines.'] },
  { id: 'delilah', name: 'Delilah', e: '✂️', title: 'Betrayer of Samson', t: 'OT', g: 'f', tags: '',
    clues: ['I lived in the Valley of Sorek.', 'Each Philistine ruler offered me 1,100 pieces of silver.', 'I kept asking the secret of a strongman\'s strength.', 'I had Samson\'s hair cut while he slept.'] },
  { id: 'ruth', name: 'Ruth', e: '🌾', title: 'Loyal daughter-in-law', t: 'OT', g: 'f', tags: 'foreign bookname',
    clues: ['I became the great-grandmother of King David.', 'I gleaned grain in the field of Boaz.', 'I was a Moabite.', 'I said, "Where you go I will go."'] },
  { id: 'naomi', name: 'Naomi', e: '🏠', title: 'Mother-in-law of Ruth', t: 'OT', g: 'f', tags: '',
    clues: ['I lost my husband Elimelech and both my sons.', 'I said, "Call me Mara."', 'I returned from Moab to Bethlehem.', 'Ruth refused to leave me.'] },
  { id: 'boaz', name: 'Boaz', e: '🌾', title: 'Kinsman-redeemer', t: 'OT', g: 'm', tags: '',
    clues: ['My mother was Rahab.', 'I let a young widow glean extra grain in my fields.', 'I became the great-grandfather of David.', 'I married Ruth.'] },
  { id: 'hannah', name: 'Hannah', e: '🙏', title: 'Mother of Samuel', t: 'OT', g: 'f', tags: '',
    clues: ['My husband\'s other wife was Peninnah.', 'Eli thought I was drunk while I prayed.', 'I made my son a little robe each year.', 'I prayed for a son and named him Samuel.'] },
  { id: 'eli', name: 'Eli', e: '🪔', title: 'Priest of Shiloh', t: 'OT', g: 'm', tags: 'priest',
    clues: ['My sons were Hophni and Phinehas.', 'I fell backward and broke my neck when I heard the ark was captured.', 'I told a boy to say, "Speak, LORD, for your servant is listening."', 'I raised Samuel at the house of the LORD in Shiloh.'] },
  { id: 'samuel', name: 'Samuel', e: '👂', title: 'Prophet and judge', t: 'OT', g: 'm', tags: 'prophet bookname',
    clues: ['My mother was Hannah.', 'I grew up serving in the tabernacle at Shiloh.', 'God called my name in the night.', 'I anointed both Saul and David as kings.'] },
  { id: 'saul', name: 'King Saul', e: '🗡️', title: 'First king of Israel', t: 'OT', g: 'm', tags: 'royal warrior',
    clues: ['I consulted a medium at Endor.', 'I was taller than anyone else in Israel.', 'I threw a spear at David while he played the harp.', 'I was the first king of Israel.'] },
  { id: 'jonathan', name: 'Jonathan', e: '🏹', title: 'Prince and friend', t: 'OT', g: 'm', tags: 'royal warrior',
    clues: ['I climbed a cliff with my armour-bearer to attack a Philistine outpost.', 'I used arrows to send a secret warning.', 'I was King Saul\'s son.', 'I was David\'s closest friend.'] },
  { id: 'david', name: 'King David', e: '🎵', title: 'Shepherd king', t: 'OT', g: 'm', tags: 'royal warrior shepherd author',
    clues: ['I danced before the LORD as the ark came to Jerusalem.', 'I played the harp for King Saul.', 'I wrote many of the Psalms.', 'I defeated Goliath with a sling and a stone.'] },
  { id: 'goliath', name: 'Goliath', e: '🛡️', title: 'Giant of Gath', t: 'OT', g: 'm', tags: 'foreign warrior',
    clues: ['My spear shaft was like a weaver\'s beam.', 'I challenged Israel for forty days.', 'I was a Philistine champion from Gath.', 'A shepherd boy struck me down with a stone.'] },
  { id: 'abigail', name: 'Abigail', e: '🍞', title: 'Wise peacemaker', t: 'OT', g: 'f', tags: '',
    clues: ['My first husband\'s name means "fool".', 'I loaded donkeys with bread, wine and figs.', 'I stopped David from taking revenge.', 'I married David after Nabal died.'] },
  { id: 'bathsheba', name: 'Bathsheba', e: '👑', title: 'Queen mother', t: 'OT', g: 'f', tags: 'royal',
    clues: ['I helped secure the throne for my son.', 'My first husband was Uriah the Hittite.', 'A king saw me from his rooftop.', 'I was the mother of King Solomon.'] },
  { id: 'nathan', name: 'Nathan', e: '🐑', title: 'Court prophet', t: 'OT', g: 'm', tags: 'prophet',
    clues: ['I helped make Solomon king.', 'I told a story about a poor man\'s little lamb.', 'I said to the king, "You are the man!"', 'I confronted David about Bathsheba.'] },
  { id: 'absalom', name: 'Absalom', e: '🌳', title: 'Rebel prince', t: 'OT', g: 'm', tags: 'royal warrior',
    clues: ['I stole the hearts of the people at the city gate.', 'I rebelled against my father.', 'I was famous for my beautiful hair.', 'My hair caught in an oak tree during battle.'] },
  { id: 'solomon', name: 'King Solomon', e: '🏛️', title: 'Wisest king', t: 'OT', g: 'm', tags: 'royal author dream',
    clues: ['I had 700 wives and 300 concubines.', 'The Queen of Sheba came to test me.', 'I built the first temple in Jerusalem.', 'God gave me great wisdom after I asked for it in a dream.'] },
  { id: 'sheba', name: 'Queen of Sheba', e: '💎', title: 'Visiting queen', t: 'OT', g: 'f', tags: 'royal foreign',
    clues: ['Jesus said I would rise at the judgment.', 'I brought spices, gold and precious stones.', 'I tested a king with hard questions.', 'I travelled to visit Solomon.'] },
  { id: 'elijah', name: 'Elijah', e: '🔥', title: 'Prophet of fire', t: 'OT', g: 'm', tags: 'prophet miracle angel water',
    clues: ['A widow\'s flour and oil never ran out while I stayed with her.', 'Ravens brought me food by a brook.', 'I called down fire on Mount Carmel.', 'I was taken to heaven in a whirlwind.'] },
  { id: 'elisha', name: 'Elisha', e: '🪓', title: 'Successor of Elijah', t: 'OT', g: 'm', tags: 'prophet miracle water',
    clues: ['I was ploughing with twelve yoke of oxen when I was called.', 'I asked for a double portion of my master\'s spirit.', 'I made an axe head float.', 'I told Naaman to wash seven times in the Jordan.'] },
  { id: 'jezebel', name: 'Jezebel', e: '🐕', title: 'Wicked queen', t: 'OT', g: 'f', tags: 'royal foreign',
    clues: ['I was a princess from Sidon.', 'I arranged the death of Naboth to seize his vineyard.', 'I threatened to kill Elijah.', 'I was the wife of King Ahab.'] },
  { id: 'ahab', name: 'King Ahab', e: '🍇', title: 'King of Israel', t: 'OT', g: 'm', tags: 'royal warrior',
    clues: ['I was killed by an arrow shot at random.', 'I sulked because Naboth would not sell his vineyard.', 'Elijah called me the troubler of Israel.', 'My wife was Jezebel.'] },
  { id: 'naaman', name: 'Naaman', e: '🌊', title: 'Aramean commander', t: 'OT', g: 'm', tags: 'foreign warrior water',
    clues: ['A young Israelite servant girl told my wife about a prophet.', 'I was a commander of the army of Aram.', 'I had leprosy.', 'I was healed after dipping seven times in the Jordan.'] },
  { id: 'hezekiah', name: 'King Hezekiah', e: '🕰️', title: 'King of Judah', t: 'OT', g: 'm', tags: 'royal',
    clues: ['I built a tunnel to bring water into Jerusalem.', 'I destroyed the bronze snake Moses had made.', 'God gave me fifteen more years of life.', 'The shadow on the stairway went backward as a sign for me.'] },
  { id: 'josiah', name: 'King Josiah', e: '📜', title: 'Boy king', t: 'OT', g: 'm', tags: 'royal warrior',
    clues: ['I died in battle at Megiddo.', 'I held a great Passover celebration.', 'The Book of the Law was found during my reign.', 'I became king when I was eight years old.'] },
  { id: 'isaiah', name: 'Isaiah', e: '🔥', title: 'Prophet of the Messiah', t: 'OT', g: 'm', tags: 'prophet author bookname angel dream',
    clues: ['I walked barefoot for three years as a sign.', 'A seraph touched my lips with a burning coal.', 'I said, "Here am I. Send me!"', 'I prophesied, "For to us a child is born."'] },
  { id: 'jeremiah', name: 'Jeremiah', e: '😢', title: 'Weeping prophet', t: 'OT', g: 'm', tags: 'prophet author bookname prison egypt',
    clues: ['I bought a field while Jerusalem was under siege.', 'I watched a potter reshape clay.', 'I was lowered into a muddy cistern.', 'I am known as the weeping prophet.'] },
  { id: 'ezekiel', name: 'Ezekiel', e: '🦴', title: 'Prophet in exile', t: 'OT', g: 'm', tags: 'prophet priest author bookname dream prison',
    clues: ['I lay on my side for 390 days as a sign.', 'I saw wheels within wheels.', 'I ate a scroll that tasted like honey.', 'I prophesied to a valley of dry bones.'] },
  { id: 'daniel', name: 'Daniel', e: '🦁', title: 'Faithful exile', t: 'OT', g: 'm', tags: 'prophet author bookname dream prison angel renamed',
    clues: ['I was renamed Belteshazzar.', 'I refused the king\'s food and ate vegetables.', 'I read the writing on the wall.', 'I was thrown into a den of lions.'] },
  { id: 'shadrach', name: 'Shadrach', e: '🔥', title: 'Furnace survivor', t: 'OT', g: 'm', tags: 'prison angel renamed',
    clues: ['My Hebrew name was Hananiah.', 'I refused to bow to a golden statue.', 'A fourth man was seen walking with us in the fire.', 'I was thrown into the fiery furnace with Meshach and Abednego.'] },
  { id: 'nebuchadnezzar', name: 'Nebuchadnezzar', e: '🗿', title: 'King of Babylon', t: 'OT', g: 'm', tags: 'royal foreign warrior dream',
    clues: ['I destroyed Jerusalem and its temple.', 'I ate grass like an ox for a time.', 'I set up a golden statue ninety feet tall.', 'I dreamed of a statue with a head of gold.'] },
  { id: 'esther', name: 'Queen Esther', e: '👸', title: 'Queen of Persia', t: 'OT', g: 'f', tags: 'royal bookname renamed',
    clues: ['My Hebrew name was Hadassah.', 'My cousin Mordecai raised me.', 'I said, "If I perish, I perish."', 'I became queen "for such a time as this".'] },
  { id: 'mordecai', name: 'Mordecai', e: '🐎', title: 'Cousin of Esther', t: 'OT', g: 'm', tags: '',
    clues: ['I uncovered a plot to kill King Xerxes.', 'I refused to bow down to Haman.', 'Haman had to lead me through the city on the king\'s horse.', 'I raised my cousin Esther.'] },
  { id: 'nehemiah', name: 'Nehemiah', e: '🧱', title: 'Wall builder', t: 'OT', g: 'm', tags: 'author bookname',
    clues: ['My builders worked with a tool in one hand and a weapon in the other.', 'I was cupbearer to King Artaxerxes.', 'I prayed before answering the king.', 'I led the rebuilding of Jerusalem\'s walls in 52 days.'] },
  { id: 'ezra', name: 'Ezra', e: '📖', title: 'Scribe', t: 'OT', g: 'm', tags: 'priest author bookname',
    clues: ['I was too ashamed to ask the king for soldiers to protect us.', 'I was a scribe skilled in the Law of Moses.', 'I led a group of exiles back from Babylon.', 'I read the Law aloud from a wooden platform.'] },
  { id: 'job', name: 'Job', e: '🌪️', title: 'Patient sufferer', t: 'OT', g: 'm', tags: 'bookname shepherd',
    clues: ['I owned 7,000 sheep and 3,000 camels.', 'Three friends sat with me in silence for seven days.', 'I said, "The LORD gave and the LORD has taken away."', 'I lost everything but never cursed God.'] },
  { id: 'jonah', name: 'Jonah', e: '🐋', title: 'Reluctant prophet', t: 'OT', g: 'm', tags: 'prophet author bookname water',
    clues: ['I was angry when a plant that shaded me withered.', 'I boarded a ship heading to Tarshish.', 'I was thrown overboard in a storm.', 'I spent three days inside a great fish.'] },
  { id: 'hosea', name: 'Hosea', e: '💔', title: 'Prophet of faithful love', t: 'OT', g: 'm', tags: 'prophet author bookname',
    clues: ['One of my children was named Lo-Ammi.', 'I bought my wife back for silver and barley.', 'My marriage pictured God\'s love for unfaithful Israel.', 'I married Gomer.'] },
  { id: 'balaam', name: 'Balaam', e: '🫏', title: 'Hired prophet', t: 'OT', g: 'm', tags: 'prophet foreign angel',
    clues: ['I came from Pethor near the Euphrates.', 'King Balak hired me.', 'I could only bless Israel when I tried to curse them.', 'My donkey talked to me.'] },

  // ── New Testament ──────────────────────────────────────────────
  { id: 'mary', name: 'Mary, mother of Jesus', e: '🤍', title: 'Mother of Jesus', t: 'NT', g: 'f', tags: 'gospels angel egypt',
    clues: ['I stood near the cross with the beloved disciple.', 'I sang, "My soul magnifies the Lord."', 'The angel Gabriel visited me in Nazareth.', 'I gave birth to Jesus in Bethlehem.'] },
  { id: 'joseph_nt', name: 'Joseph the carpenter', e: '🪚', title: 'Husband of Mary', t: 'NT', g: 'm', tags: 'gospels angel dream egypt',
    clues: ['I was a descendant of King David.', 'I planned to divorce my fiancée quietly.', 'An angel warned me in a dream to flee to Egypt.', 'I was the carpenter who raised Jesus.'] },
  { id: 'elizabeth', name: 'Elizabeth', e: '👶', title: 'Mother of John', t: 'NT', g: 'f', tags: 'gospels',
    clues: ['My husband was a priest named Zechariah.', 'I was old when I became pregnant.', 'My baby leaped in my womb when Mary greeted me.', 'I was the mother of John the Baptist.'] },
  { id: 'zechariah', name: 'Zechariah', e: '🤐', title: 'Priest', t: 'NT', g: 'm', tags: 'gospels priest angel',
    clues: ['I was burning incense in the temple.', 'The angel Gabriel appeared to me.', 'I could not speak until my son was named.', 'I wrote, "His name is John."'] },
  { id: 'john_baptist', name: 'John the Baptist', e: '🦗', title: 'Forerunner', t: 'NT', g: 'm', tags: 'gospels prophet water prison',
    clues: ['Herod Antipas had me beheaded.', 'I wore camel hair and ate locusts and wild honey.', 'I said, "Behold, the Lamb of God!"', 'I baptized Jesus in the Jordan River.'] },
  { id: 'simeon', name: 'Simeon', e: '🕊️', title: 'Righteous man', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['I told Mary a sword would pierce her soul.', 'I was promised I would not die before seeing the Messiah.', 'I held the baby Jesus in the temple.', 'I prayed, "Now dismiss your servant in peace."'] },
  { id: 'anna', name: 'Anna', e: '⌛', title: 'Prophetess', t: 'NT', g: 'f', tags: 'gospels prophet',
    clues: ['I was from the tribe of Asher.', 'I was a widow of about 84.', 'I never left the temple, worshipping with fasting and prayer.', 'I spoke about the baby Jesus to all who looked for redemption.'] },
  { id: 'peter', name: 'Peter', e: '🔑', title: 'The Rock', t: 'NT', g: 'm', tags: 'gospels apostle author bookname renamed water miracle prison angel dream',
    clues: ['I saw a vision of a sheet full of animals.', 'An angel led me out of prison.', 'I walked on water, then began to sink.', 'I denied Jesus three times before the rooster crowed.'] },
  { id: 'andrew', name: 'Andrew', e: '🐟', title: 'Fisherman apostle', t: 'NT', g: 'm', tags: 'gospels apostle water',
    clues: ['I was first a disciple of John the Baptist.', 'I brought a boy with five loaves and two fish to Jesus.', 'I brought my brother to meet Jesus.', 'I am Simon Peter\'s brother.'] },
  { id: 'james', name: 'James, son of Zebedee', e: '⚡', title: 'Son of Thunder', t: 'NT', g: 'm', tags: 'gospels apostle water',
    clues: ['Herod had me put to death with the sword.', 'I saw Jesus transfigured on the mountain.', 'Jesus called my brother and me "Sons of Thunder".', 'I left my father\'s fishing boat with my brother John.'] },
  { id: 'john', name: 'John the Apostle', e: '📜', title: 'Beloved disciple', t: 'NT', g: 'm', tags: 'gospels apostle author bookname water dream prison angel',
    clues: ['I outran Peter to the empty tomb.', 'Jesus asked me to care for his mother.', 'I received the Revelation on the island of Patmos.', 'I wrote, "God is love."'] },
  { id: 'matthew', name: 'Matthew', e: '💰', title: 'Tax collector apostle', t: 'NT', g: 'm', tags: 'gospels apostle author bookname renamed',
    clues: ['I was also called Levi.', 'I hosted a big dinner with tax collectors and sinners.', 'Jesus called me from my tax booth.', 'I wrote the first Gospel in the New Testament.'] },
  { id: 'thomas', name: 'Thomas', e: '🤔', title: 'The twin', t: 'NT', g: 'm', tags: 'gospels apostle',
    clues: ['I said, "Let us also go, that we may die with him."', 'I was called Didymus, the Twin.', 'I said, "My Lord and my God!"', 'I would not believe until I touched Jesus\' wounds.'] },
  { id: 'judas', name: 'Judas Iscariot', e: '🪙', title: 'The betrayer', t: 'NT', g: 'm', tags: 'gospels apostle',
    clues: ['I complained that perfume should have been sold for the poor.', 'I kept the disciples\' money bag.', 'I was paid thirty pieces of silver.', 'I betrayed Jesus with a kiss.'] },
  { id: 'paul', name: 'Paul', e: '✉️', title: 'Apostle to the Gentiles', t: 'NT', g: 'm', tags: 'apostle author renamed prison water miracle angel dream',
    clues: ['I was a tentmaker and a Roman citizen.', 'A viper bit me on Malta and I was unharmed.', 'I wrote letters to the Romans, Corinthians and Galatians.', 'I was blinded by a light on the road to Damascus.'] },
  { id: 'barnabas', name: 'Barnabas', e: '🤝', title: 'Son of encouragement', t: 'NT', g: 'm', tags: 'renamed',
    clues: ['I was a Levite from Cyprus.', 'I argued with Paul about John Mark.', 'I sold a field and gave the money to the apostles.', 'My name means "son of encouragement".'] },
  { id: 'stephen', name: 'Stephen', e: '🪨', title: 'First martyr', t: 'NT', g: 'm', tags: 'miracle',
    clues: ['I was chosen to help distribute food to widows.', 'My face looked like the face of an angel.', 'I saw heaven open and Jesus standing at God\'s right hand.', 'I was the first Christian martyr, stoned to death.'] },
  { id: 'philip', name: 'Philip the Evangelist', e: '🛞', title: 'Evangelist', t: 'NT', g: 'm', tags: 'miracle water angel',
    clues: ['I had four unmarried daughters who prophesied.', 'I preached in Samaria.', 'An angel sent me to a desert road.', 'I explained Isaiah to an Ethiopian official in a chariot.'] },
  { id: 'eunuch', name: 'Ethiopian official', e: '📖', title: 'Treasurer of Candace', t: 'NT', g: 'm', tags: 'foreign water',
    clues: ['I had been to Jerusalem to worship.', 'I served Candace, queen of the Ethiopians.', 'I was reading Isaiah in my chariot.', 'Philip baptized me on the road to Gaza.'] },
  { id: 'mary_magdalene', name: 'Mary Magdalene', e: '🌅', title: 'Witness of the resurrection', t: 'NT', g: 'f', tags: 'gospels angel',
    clues: ['I supported Jesus\' ministry from my own means.', 'Jesus cast seven demons out of me.', 'I thought the risen Jesus was the gardener.', 'I was the first to see Jesus after his resurrection.'] },
  { id: 'martha', name: 'Martha', e: '🍽️', title: 'The busy host', t: 'NT', g: 'f', tags: 'gospels',
    clues: ['I said, "I believe that you are the Christ, the Son of God."', 'I complained that my sister was not helping.', 'I was distracted by much serving.', 'My brother was Lazarus.'] },
  { id: 'mary_bethany', name: 'Mary of Bethany', e: '🏺', title: 'Worshipper', t: 'NT', g: 'f', tags: 'gospels',
    clues: ['Jesus said I had chosen the good part.', 'I sat at Jesus\' feet listening.', 'I wiped Jesus\' feet with my hair.', 'I anointed Jesus with expensive nard.'] },
  { id: 'lazarus', name: 'Lazarus', e: '⚰️', title: 'Raised from the dead', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['The chief priests plotted to kill me too.', 'My sisters were Martha and Mary.', 'Jesus wept at my tomb.', 'I was raised after four days in the tomb.'] },
  { id: 'nicodemus', name: 'Nicodemus', e: '🌙', title: 'Pharisee', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['I brought about 75 pounds of myrrh and aloes.', 'I was a member of the Jewish ruling council.', 'I asked how a man can be born when he is old.', 'I came to Jesus at night.'] },
  { id: 'zacchaeus', name: 'Zacchaeus', e: '🌳', title: 'Chief tax collector', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['I promised to give half my goods to the poor.', 'I lived in Jericho.', 'I was a short, rich chief tax collector.', 'I climbed a sycamore tree to see Jesus.'] },
  { id: 'pilate', name: 'Pontius Pilate', e: '🧼', title: 'Roman governor', t: 'NT', g: 'm', tags: 'gospels foreign',
    clues: ['My wife warned me about a dream.', 'I asked, "What is truth?"', 'I had a sign written: "King of the Jews".', 'I washed my hands before the crowd.'] },
  { id: 'herod', name: 'Herod the Great', e: '🏰', title: 'King of Judea', t: 'NT', g: 'm', tags: 'gospels royal foreign',
    clues: ['I rebuilt the temple in Jerusalem on a grand scale.', 'I was an Idumean ruling for Rome.', 'Wise men from the East came to my palace.', 'I ordered the killing of the baby boys in Bethlehem.'] },
  { id: 'simon_cyrene', name: 'Simon of Cyrene', e: '✝️', title: 'Cross bearer', t: 'NT', g: 'm', tags: 'gospels foreign',
    clues: ['My sons were Alexander and Rufus.', 'I was coming in from the countryside.', 'I came from Cyrene in North Africa.', 'I was forced to carry Jesus\' cross.'] },
  { id: 'samaritan_woman', name: 'The Samaritan woman', e: '🪣', title: 'Woman at the well', t: 'NT', g: 'f', tags: 'gospels foreign water',
    clues: ['Many in my town of Sychar believed because of my testimony.', 'I had had five husbands.', 'Jesus offered me living water.', 'I met Jesus at Jacob\'s well.'] },
  { id: 'jairus', name: 'Jairus', e: '🛏️', title: 'Synagogue leader', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['A sick woman was healed while Jesus was on the way to my house.', 'I was a ruler of the synagogue.', 'Jesus said to my daughter, "Talitha koum."', 'Jesus raised my twelve-year-old daughter.'] },
  { id: 'bartimaeus', name: 'Bartimaeus', e: '🦯', title: 'Blind beggar', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['I threw off my cloak and jumped up.', 'People told me to be quiet but I shouted louder.', 'I sat begging by the road outside Jericho.', 'Jesus healed my blindness.'] },
  { id: 'joseph_arimathea', name: 'Joseph of Arimathea', e: '🪨', title: 'Secret disciple', t: 'NT', g: 'm', tags: 'gospels',
    clues: ['I was a rich member of the council.', 'I asked Pilate for Jesus\' body.', 'I wrapped Jesus in clean linen.', 'Jesus was laid in my new tomb.'] },
  { id: 'lydia', name: 'Lydia', e: '🟣', title: 'Seller of purple', t: 'NT', g: 'f', tags: 'foreign water',
    clues: ['I came from the city of Thyatira.', 'I met Paul at a place of prayer by a river.', 'I sold purple cloth.', 'I was the first recorded convert in Philippi.'] },
  { id: 'priscilla', name: 'Priscilla', e: '⛺', title: 'Teacher and tentmaker', t: 'NT', g: 'f', tags: '',
    clues: ['Claudius ordered us to leave Rome.', 'My husband and I explained God\'s way more accurately to Apollos.', 'We hosted a church in our home.', 'I made tents with my husband Aquila.'] },
  { id: 'timothy', name: 'Timothy', e: '📨', title: 'Young pastor', t: 'NT', g: 'm', tags: 'bookname',
    clues: ['My father was Greek.', 'My grandmother Lois and mother Eunice taught me the Scriptures.', 'Paul called me his true son in the faith.', 'Paul wrote two letters to me.'] },
  { id: 'luke', name: 'Luke', e: '🩺', title: 'The physician', t: 'NT', g: 'm', tags: 'author bookname foreign',
    clues: ['I wrote to "most excellent Theophilus".', 'I travelled with Paul, writing "we" in parts of my account.', 'Paul called me the beloved physician.', 'I wrote a Gospel and the book of Acts.'] },
  { id: 'cornelius', name: 'Cornelius', e: '⚔️', title: 'Centurion', t: 'NT', g: 'm', tags: 'foreign warrior angel dream',
    clues: ['I was known for giving generously to the poor.', 'I was a centurion of the Italian Regiment.', 'An angel told me to send for Peter.', 'My household was among the first Gentiles to receive the Holy Spirit.'] },
  { id: 'silas', name: 'Silas', e: '🎶', title: 'Missionary partner', t: 'NT', g: 'm', tags: 'prison',
    clues: ['I carried the letter from the Jerusalem council to Antioch.', 'I travelled with Paul on his second journey.', 'An earthquake opened our prison doors.', 'I sang hymns with Paul in a Philippian jail at midnight.'] },
  { id: 'tabitha', name: 'Tabitha (Dorcas)', e: '🧵', title: 'Disciple of Joppa', t: 'NT', g: 'f', tags: '',
    clues: ['Widows showed Peter the clothes I had made.', 'I lived in Joppa.', 'I was always doing good and helping the poor.', 'Peter raised me from the dead.'] },
];

// Guess Who questions. Each maps to a predicate over a person.
export const GUESS_WHO_QUESTIONS = [
  { id: 'female', text: 'Is your person a woman?', test: (p) => p.g === 'f' },
  { id: 'nt', text: 'Are they from the New Testament?', test: (p) => p.t === 'NT' },
  { id: 'genesis', text: 'Do they appear in Genesis?', test: (p) => has(p, 'genesis') },
  { id: 'gospels', text: 'Do they appear in the four Gospels?', test: (p) => has(p, 'gospels') },
  { id: 'royal', text: 'Are they royalty (king, queen or prince)?', test: (p) => has(p, 'royal') },
  { id: 'prophet', text: 'Were they a prophet or prophetess?', test: (p) => has(p, 'prophet') },
  { id: 'apostle', text: 'Were they an apostle (the Twelve or Paul)?', test: (p) => has(p, 'apostle') },
  { id: 'priest', text: 'Were they a priest?', test: (p) => has(p, 'priest') },
  { id: 'author', text: 'Did they (traditionally) write a book of the Bible?', test: (p) => has(p, 'author') },
  { id: 'bookname', text: 'Is a book of the Bible named after them?', test: (p) => has(p, 'bookname') },
  { id: 'angel', text: 'Did they meet or see an angel?', test: (p) => has(p, 'angel') },
  { id: 'miracle', text: 'Did God work miracles through them?', test: (p) => has(p, 'miracle') },
  { id: 'water', text: 'Does a key moment happen at a sea, river or well?', test: (p) => has(p, 'water') },
  { id: 'renamed', text: 'Were they given a new name?', test: (p) => has(p, 'renamed') },
  { id: 'foreign', text: 'Were they a non-Israelite (Gentile)?', test: (p) => has(p, 'foreign') },
  { id: 'shepherd', text: 'Did they keep sheep or flocks?', test: (p) => has(p, 'shepherd') },
  { id: 'warrior', text: 'Did they fight in battles?', test: (p) => has(p, 'warrior') },
  { id: 'egypt', text: 'Did they spend time in Egypt?', test: (p) => has(p, 'egypt') },
  { id: 'prison', text: 'Were they ever imprisoned or taken captive?', test: (p) => has(p, 'prison') },
  { id: 'dream', text: 'Did they have or interpret dreams or visions?', test: (p) => has(p, 'dream') },
];

function has(p, tag) {
  return (' ' + p.tags + ' ').includes(' ' + tag + ' ');
}
