// Christian songs from around the world, used by "Name That Song", "Who Sings It?"
// and "Where's It From?". We store titles, artists and facts only — clues are written
// in our own words (no copyrighted lyrics). Public-domain lyrics live in hymns.js.
//
// t: title, a: artist / writer, c: country, r: region, y: year (approx. first release,
// omitted when uncertain), l: language, e: emoji hint, k: kind, alt: accepted aliases,
// d: descriptive clue (paraphrase of the theme — never quoted lyrics).

export const SONGS = [
  // ── Africa: Nigeria ────────────────────────────────────────────
  { t: 'Way Maker', a: 'Sinach', c: 'Nigeria', r: 'Africa', y: 2015, l: 'English', e: '🛣️✨🙌', k: 'afro',
    d: 'A Nigerian worship anthem, later covered worldwide, that names God as miracle worker, promise keeper and light in the darkness.' },
  { t: 'I Know Who I Am', a: 'Sinach', c: 'Nigeria', r: 'Africa', l: 'English', e: '🪪👑🙋', k: 'afro',
    d: 'An identity anthem about being chosen, a royal priesthood, and belonging to God.' },
  { t: 'Great Are You Lord', a: 'Sinach', c: 'Nigeria', r: 'Africa', l: 'English', e: '🙌⛰️👑', k: 'afro',
    d: 'A Nigerian praise song exalting how great and mighty God is. (Not the All Sons & Daughters song with a similar name!)' },
  { t: 'Imela', a: 'Nathaniel Bassey', c: 'Nigeria', r: 'Africa', y: 2015, l: 'Igbo / English', e: '🙏💛🎺', k: 'afro',
    d: 'Its Igbo title means "thank you" — a trumpet-playing worship leader\'s song of gratitude.' },
  { t: 'Onise Iyanu', a: 'Nathaniel Bassey', c: 'Nigeria', r: 'Africa', l: 'Yoruba / English', e: '✨🪄🙌', k: 'afro',
    d: 'A Yoruba title meaning "miracle worker" — celebrating the God who does wonders.' },
  { t: 'Olowogbogboro', a: 'Nathaniel Bassey', c: 'Nigeria', r: 'Africa', y: 2020, l: 'Yoruba / English', e: '💪🦾🌍', k: 'afro',
    d: 'A Yoruba name for God meaning "the One with the long, mighty arm". Features Joe Mettle and Dunsin Oyekan.' },
  { t: 'Excess Love', a: 'Mercy Chinwo', c: 'Nigeria', r: 'Africa', y: 2019, l: 'English / Igbo', e: '❤️➕➕✝️', k: 'afro',
    d: 'A ballad marvelling that Jesus loved us so much He gave His life — love beyond measure.' },
  { t: 'Obinasom', a: 'Mercy Chinwo', c: 'Nigeria', r: 'Africa', l: 'Igbo', e: '🫀🏠🙏', k: 'afro',
    d: 'An Igbo worship song by the singer who won Nigerian Idol before becoming a gospel star.' },
  { t: 'Chinedum', a: 'Mercy Chinwo', c: 'Nigeria', r: 'Africa', l: 'Igbo', e: '🧭👣🙏', k: 'afro',
    d: 'An Igbo title meaning "God leads me".' },
  { t: 'Too Faithful', a: 'Moses Bliss', c: 'Nigeria', r: 'Africa', y: 2020, l: 'English', e: '🤝💯🙏', k: 'afro',
    d: 'A testimony song declaring that God has been faithful again and again.' },
  { t: 'Bigger Everyday', a: 'Moses Bliss', c: 'Nigeria', r: 'Africa', l: 'English', e: '📈🙌🌅', k: 'afro',
    d: 'A joyful Nigerian song about God growing greater in the singer\'s life each day.' },
  { t: 'Fragrance to Fire', a: 'Dunsin Oyekan', c: 'Nigeria', r: 'Africa', y: 2019, l: 'English', e: '🌸➡️🔥', k: 'afro',
    d: 'A prayerful worship song asking to become an offering — from sweet aroma to burning flame.' },
  { t: 'Oruko Tuntun', a: 'Tope Alabi', c: 'Nigeria', r: 'Africa', l: 'Yoruba', e: '🆕📛🙌', k: 'afro',
    d: 'A Yoruba praise song whose title means "new name" — praising God with fresh names and titles. Features TY Bello.' },
  { t: 'Nara', a: 'Tim Godfrey', c: 'Nigeria', r: 'Africa', l: 'Igbo / English', e: '🎁🙌🇳🇬🇺🇸', k: 'afro',
    d: 'An Igbo word meaning "receive" — a Nigerian–American collaboration with Travis Greene.' },
  { t: 'Yahweh', a: 'Minister GUC', c: 'Nigeria', r: 'Africa', l: 'English', e: '🙌🔥👑', k: 'afro',
    d: 'A Nigerian worship song that simply lifts up God\'s covenant name.' },
  { t: 'Victory', a: 'Eben', c: 'Nigeria', r: 'Africa', l: 'English', e: '🏆🎉✝️', k: 'afro',
    d: 'An energetic Nigerian gospel celebration of triumph through Christ.' },
  { t: 'Under the Canopy', a: 'Frank Edwards', c: 'Nigeria', r: 'Africa', l: 'English', e: '⛺🛡️🙏', k: 'afro',
    d: 'A song about resting safely under God\'s covering, by the Nigerian "Rocktown" gospel artist.' },
  { t: 'See What the Lord Has Done', a: 'Nathaniel Bassey', c: 'Nigeria', r: 'Africa', l: 'English', e: '👀🙌🎺', k: 'afro',
    d: 'A testimony song inviting everyone to look at God\'s wonderful works.' },

  // ── Africa: Ghana ───────────────────────────────────────────────
  { t: 'Adom', a: 'Diana Hamilton', c: 'Ghana', r: 'Africa', y: 2019, l: 'Twi', e: '🎁💛🇬🇭', k: 'afro',
    d: 'A Twi title meaning "grace" — a huge Ghanaian hit about God\'s unmerited favour.' },
  { t: 'The Doing of the Lord', a: 'Diana Hamilton', c: 'Ghana', r: 'Africa', l: 'English / Twi', e: '🛠️✨🙌', k: 'afro',
    d: 'A Ghanaian song marvelling at what God has done; a later version features Mercy Chinwo.' },
  { t: 'Waye Me Yie', a: 'Piesie Esther', c: 'Ghana', r: 'Africa', y: 2020, l: 'Twi', e: '🙏😊🇬🇭', k: 'afro',
    d: 'A Twi thanksgiving song meaning "You have done well for me".' },
  { t: 'Bo Noo Ni', a: 'Joe Mettle', c: 'Ghana', r: 'Africa', l: 'Ga', e: '🙌🗣️🇬🇭', k: 'afro',
    d: 'A Ga-language worship song from one of Ghana\'s leading gospel singers.' },
  { t: 'Baba', a: 'Sonnie Badu', c: 'Ghana', r: 'Africa', l: 'Twi / English', e: '👨‍👧🙌🌍', k: 'afro',
    d: 'Named after a word for "Father" — a worship song by the Ghanaian-British "Rockhill" worship leader.' },
  { t: 'Aseda', a: 'Nacee', c: 'Ghana', r: 'Africa', l: 'Twi', e: '🙏🎶🥁', k: 'afro',
    d: 'A Twi title meaning "thanksgiving" — a danceable Ghanaian gospel tune.' },

  // ── Africa: East ────────────────────────────────────────────────
  { t: 'Nibebe', a: 'Rose Muhando', c: 'Tanzania', r: 'Africa', l: 'Swahili', e: '🤱🙏🇹🇿', k: 'afro',
    d: 'A Swahili plea asking God to "carry me" — by the Tanzanian queen of gospel.' },
  { t: 'Shusha Nyavu', a: 'Christina Shusho', c: 'Tanzania', r: 'Africa', l: 'Swahili', e: '🎣🌊🙌', k: 'afro',
    d: 'Swahili for "let down the nets" — inspired by Peter\'s miraculous catch of fish.' },
  { t: 'Nikumbushe Wema Wako', a: 'Angel Benard', c: 'Tanzania', r: 'Africa', l: 'Swahili', e: '🧠💭💛', k: 'afro',
    d: 'A Swahili prayer asking God to "remind me of Your goodness".' },
  { t: 'Ipo Siku', a: 'Goodluck Gozbert', c: 'Tanzania', r: 'Africa', l: 'Swahili', e: '📅🌅🙏', k: 'afro',
    d: 'Swahili for "there is a day" — a hopeful song that God\'s time will come.' },
  { t: 'Mwema', a: 'Mercy Masika', c: 'Kenya', r: 'Africa', l: 'Swahili', e: '💛🙏🇰🇪', k: 'afro',
    d: 'A Kenyan worship song whose Swahili title means "Good One" — celebrating God\'s goodness.' },
  { t: 'Mbona', a: 'Daddy Owen', c: 'Kenya', r: 'Africa', l: 'Swahili', e: '❓😢➡️🙏', k: 'afro',
    d: 'Swahili for "why?" — a Kenyan song about bringing hard questions to God.' },

  // ── Africa: Southern & Central ──────────────────────────────────
  { t: 'Shwele Baba', a: 'Rebecca Malope', c: 'South Africa', r: 'Africa', l: 'Zulu', e: '🙏😔🇿🇦', k: 'afro',
    d: 'A Zulu cry for mercy — "forgive me, Father" — by South Africa\'s "Queen of Gospel".' },
  { t: 'Mphefumlo Wami', a: 'Lundi Tyamara', c: 'South Africa', r: 'Africa', l: 'Xhosa', e: '🫁🙌🇿🇦', k: 'afro',
    d: 'Xhosa for "my soul" — a beloved South African gospel classic.' },
  { t: 'Tango Na Ngai', a: 'Moise Mbiye', c: 'DR Congo', r: 'Africa', l: 'Lingala', e: '⏰🙏🇨🇩', k: 'afro',
    d: 'A Lingala title meaning "my time" — a Congolese song about God\'s perfect timing.' },
  { t: 'Nkosi Sikelel\' iAfrika', a: 'Enoch Sontonga', c: 'South Africa', r: 'Africa', y: 1897, l: 'Xhosa / Zulu', e: '🙏🌍🇿🇦', k: 'hymn',
    alt: ['Nkosi Sikelel iAfrika', 'God Bless Africa'],
    d: 'A Xhosa hymn — "Lord, bless Africa" — that became part of national anthems across the continent.' },
  { t: 'Siyahamba', a: 'Traditional (South Africa)', c: 'South Africa', r: 'Africa', l: 'Zulu', e: '🚶‍♀️💡🌍', k: 'hymn',
    alt: ['We Are Marching in the Light of God', 'We Are Marching'],
    d: 'A Zulu chorus about walking in God\'s light, sung by choirs all over the world.' },
  { t: 'Thuma Mina', a: 'Traditional (South Africa)', c: 'South Africa', r: 'Africa', l: 'Zulu', e: '📨🙋🌍', k: 'hymn',
    alt: ['Send Me Lord', 'Send Me Jesus'],
    d: 'A short Zulu chorus meaning "send me" — a prayer of willing service.' },
  { t: 'Machira Machena', a: 'Charles Charamba', c: 'Zimbabwe', r: 'Africa', l: 'Shona', e: '👕⚪🇿🇼', k: 'afro',
    d: 'A Shona gospel song about white garments, by a Zimbabwean gospel star and pastor.' },

  // ── North America ───────────────────────────────────────────────
  { t: 'How Great Is Our God', a: 'Chris Tomlin', c: 'USA', r: 'North America', y: 2004, l: 'English', e: '🌌👑🎸', k: 'worship',
    d: 'A modern worship staple about God\'s splendour, clothed in majesty — sung in many languages at once in later versions.' },
  { t: 'Reckless Love', a: 'Cory Asbury', c: 'USA', r: 'North America', y: 2017, l: 'English', e: '🐑🏃‍♂️❤️', k: 'worship',
    d: 'A song about a love that leaves the ninety-nine to chase down the one.' },
  { t: 'Goodness of God', a: 'Bethel Music', c: 'USA', r: 'North America', y: 2019, l: 'English', e: '🌅🙏💛', k: 'worship',
    d: 'Led by Jenn Johnson — a song about God\'s faithfulness through every season of life.' },
  { t: 'Raise a Hallelujah', a: 'Bethel Music', c: 'USA', r: 'North America', y: 2019, l: 'English', e: '🙌⚔️🎶', k: 'worship',
    d: 'Written while praying for a child\'s healing — praise used as a weapon in the battle.' },
  { t: 'No Longer Slaves', a: 'Bethel Music', c: 'USA', r: 'North America', y: 2014, l: 'English', e: '⛓️💥👨‍👧', k: 'worship',
    d: 'A declaration of freedom from fear because we are children of God.' },
  { t: 'Graves into Gardens', a: 'Elevation Worship', c: 'USA', r: 'North America', y: 2020, l: 'English', e: '🪦➡️🌷', k: 'worship',
    d: 'A song about God turning mourning into dancing and ashes into beauty.' },
  { t: 'Do It Again', a: 'Elevation Worship', c: 'USA', r: 'North America', y: 2017, l: 'English', e: '🧱🔁🙏', k: 'worship',
    d: 'A song of faith while waiting at the walls, trusting God to be faithful again.' },
  { t: 'The Blessing', a: 'Kari Jobe & Cody Carnes', c: 'USA', r: 'North America', y: 2020, l: 'English', e: '🙏✨📖', k: 'worship',
    d: 'Based on the priestly blessing of Numbers 6 — recorded in dozens of countries during 2020.' },
  { t: 'Jireh', a: 'Elevation Worship & Maverick City Music', c: 'USA', r: 'North America', y: 2021, l: 'English', e: '🎁🌸🙌', k: 'worship',
    d: 'Named after the Hebrew name meaning "the Lord will provide" — you are more than enough.' },
  { t: 'Promises', a: 'Maverick City Music', c: 'USA', r: 'North America', y: 2020, l: 'English', e: '🤝📜♾️', k: 'worship',
    d: 'A gospel-worship song celebrating that God keeps His word through every generation.' },
  { t: 'Firm Foundation (He Won\'t)', a: 'Cody Carnes', c: 'USA', r: 'North America', y: 2021, l: 'English', e: '🪨🏠💪', k: 'worship', alt: ['Firm Foundation'],
    d: 'A song about Christ as the unshakable foundation who will not fail.' },
  { t: 'Gratitude', a: 'Brandon Lake', c: 'USA', r: 'North America', y: 2022, l: 'English', e: '🙏🎶🙌', k: 'worship',
    d: 'A song admitting that our songs are never enough — but we will keep singing hallelujah.' },
  { t: 'I Can Only Imagine', a: 'MercyMe', c: 'USA', r: 'North America', y: 1999, l: 'English', e: '💭☁️👀', k: 'worship',
    d: 'A song imagining the moment of seeing Jesus face to face — later made into a film.' },
  { t: 'Lord, I Need You', a: 'Matt Maher', c: 'USA', r: 'North America', y: 2011, l: 'English', e: '🙏⏰❤️', k: 'worship',
    d: 'A song of total dependence on God, every hour.' },
  { t: 'Blessings', a: 'Laura Story', c: 'USA', r: 'North America', y: 2011, l: 'English', e: '🌧️🎁🙏', k: 'worship',
    d: 'A song asking whether our trials and raindrops might be God\'s mercies in disguise.' },
  { t: 'You Say', a: 'Lauren Daigle', c: 'USA', r: 'North America', y: 2018, l: 'English', e: '🗣️🪞💛', k: 'worship',
    d: 'A song contrasting self-doubt with what God says about who we are.' },
  { t: 'Trust in You', a: 'Lauren Daigle', c: 'USA', r: 'North America', y: 2015, l: 'English', e: '⛰️🙏🤲', k: 'worship',
    d: 'A song about trusting God even when He does not move the mountain.' },
  { t: 'Holy Spirit', a: 'Francesca Battistelli', c: 'USA', r: 'North America', y: 2014, l: 'English', e: '🕊️🔥🙌', k: 'worship',
    d: 'An invitation for God\'s presence to come — written by Bryan and Katie Torwalt.' },
  { t: 'Break Every Chain', a: 'Tasha Cobbs', c: 'USA', r: 'North America', y: 2013, l: 'English', e: '⛓️💥🗣️', k: 'gospel',
    d: 'A gospel anthem declaring power in the name of Jesus to break every chain.' },
  { t: 'Total Praise', a: 'Richard Smallwood', c: 'USA', r: 'North America', y: 1996, l: 'English', e: '⛰️👀🙌', k: 'gospel',
    d: 'A gospel classic drawn from Psalm 121 — lifting eyes to the hills, ending in a grand "Amen".' },
  { t: 'I Smile', a: 'Kirk Franklin', c: 'USA', r: 'North America', y: 2011, l: 'English', e: '😁☀️🎹', k: 'gospel',
    d: 'An upbeat gospel hit about choosing joy even on a hard day.' },
  { t: 'Stomp', a: 'Kirk Franklin', c: 'USA', r: 'North America', y: 1997, l: 'English', e: '🦶🎉🕺', k: 'gospel',
    d: 'A funky 1990s gospel crossover hit that made church kids dance.' },
  { t: 'Never Would Have Made It', a: 'Marvin Sapp', c: 'USA', r: 'North America', y: 2007, l: 'English', e: '🚫🏁➡️🙏', k: 'gospel',
    d: 'A gospel testimony: without God, I would not have made it through.' },
  { t: 'Oh Happy Day', a: 'Edwin Hawkins Singers', c: 'USA', r: 'North America', y: 1968, l: 'English', e: '😊📅🌊', k: 'gospel',
    d: 'An 18th-century hymn reworked into a 1960s gospel smash about the day Jesus washed sins away.' },
  { t: 'Take Me to the King', a: 'Tamela Mann', c: 'USA', r: 'North America', y: 2012, l: 'English', e: '👑🚶‍♀️🙏', k: 'gospel',
    d: 'A weary soul asking to be brought before the King — written by Kirk Franklin.' },
  { t: 'Made a Way', a: 'Travis Greene', c: 'USA', r: 'North America', y: 2015, l: 'English', e: '🛤️🌊🙌', k: 'gospel',
    d: 'A gospel anthem about God making a way when there seemed to be none.' },
  { t: 'Intentional', a: 'Travis Greene', c: 'USA', r: 'North America', y: 2015, l: 'English', e: '🎯🧩🙌', k: 'gospel',
    d: 'A song declaring that God is purposeful — all things work for our good.' },
  { t: 'Won\'t He Do It', a: 'Koryn Hawthorne', c: 'USA', r: 'North America', y: 2018, l: 'English', e: '✅💪🙌', k: 'gospel',
    d: 'A confident gospel song by a singer first known from a TV talent show.' },
  { t: 'Friend of God', a: 'Israel Houghton', c: 'USA', r: 'North America', l: 'English', e: '🤝😲👑', k: 'gospel',
    d: 'A song amazed that the God of the universe calls us friend.' },
  { t: 'Shackles (Praise You)', a: 'Mary Mary', c: 'USA', r: 'North America', y: 2000, l: 'English', e: '⛓️🙌💃', k: 'gospel', alt: ['Shackles', 'Praise You'],
    d: 'A sister duo\'s crossover hit: take the shackles off my feet so I can dance.' },
  { t: 'Revelation Song', a: 'Jennie Lee Riddle', c: 'USA', r: 'North America', y: 2004, l: 'English', e: '🐑👑📜', k: 'worship',
    d: 'Based on the worship around the throne in Revelation 4–5; made famous by Kari Jobe.' },
  { t: 'Holy Forever', a: 'Chris Tomlin', c: 'USA', r: 'North America', y: 2022, l: 'English', e: '♾️🙌✨', k: 'worship',
    d: 'A song joining a "thousand generations" in declaring God\'s holiness forever.' },
  { t: 'Living Hope', a: 'Phil Wickham', c: 'USA', r: 'North America', y: 2018, l: 'English', e: '🪦🌅✝️', k: 'worship',
    d: 'A resurrection song: the grave is empty and hope is alive.' },
  { t: 'Battle Belongs', a: 'Phil Wickham', c: 'USA', r: 'North America', y: 2020, l: 'English', e: '⚔️🛡️🙏', k: 'worship',
    d: 'A reminder that the fight belongs to the Lord, so we fall on our knees.' },
  { t: 'This Is Amazing Grace', a: 'Phil Wickham', c: 'USA', r: 'North America', y: 2012, l: 'English', e: '👑✝️😲', k: 'worship',
    d: 'A song about the King of glory who took the fall for us.' },
  { t: 'Awesome God', a: 'Rich Mullins', c: 'USA', r: 'North America', y: 1988, l: 'English', e: '⚡🌍👑', k: 'worship',
    d: 'A 1980s worship chorus declaring our God reigns with wisdom, power and love.' },
  { t: 'Because He Lives', a: 'Bill & Gloria Gaither', c: 'USA', r: 'North America', y: 1971, l: 'English', e: '👶🌅✝️', k: 'hymn',
    d: 'Written by a husband-and-wife songwriting team expecting a child: we can face tomorrow.' },
  { t: 'Mary, Did You Know?', a: 'Mark Lowry', c: 'USA', r: 'North America', l: 'English', e: '🤱⭐❓', k: 'worship', alt: ['Mary Did You Know'],
    d: 'A Christmas song asking the mother of Jesus if she understood who her baby was.' },
  { t: 'Open the Eyes of My Heart', a: 'Paul Baloche', c: 'USA', r: 'North America', y: 1997, l: 'English', e: '👁️❤️✨', k: 'worship',
    d: 'A prayer based on Ephesians 1 asking to see God high and lifted up.' },
  { t: 'Lord, I Lift Your Name on High', a: 'Rick Founds', c: 'USA', r: 'North America', y: 1989, l: 'English', e: '⬆️✝️⬇️', k: 'worship',
    d: 'A chorus tracing Jesus\' journey — from heaven to earth, to the cross, to the grave, to the sky.' },
  { t: 'Build My Life', a: 'Housefires', c: 'USA', r: 'North America', y: 2016, l: 'English', e: '🧱🏗️❤️', k: 'worship',
    d: 'A song about building one\'s life on the love of Jesus; written by Pat Barrett and others.' },
  { t: 'The Old Rugged Cross', a: 'George Bennard', c: 'USA', r: 'North America', y: 1912, l: 'English', e: '🪵✝️⛰️', k: 'hymn',
    d: 'An early 20th-century hymn about cherishing the cross on a hill far away.' },

  // ── Europe ─────────────────────────────────────────────────────
  { t: '10,000 Reasons (Bless the Lord)', a: 'Matt Redman', c: 'England', r: 'Europe', y: 2011, l: 'English', e: '🔟0️⃣0️⃣0️⃣🌅', k: 'worship',
    alt: ['10000 Reasons', 'Ten Thousand Reasons', 'Bless the Lord'],
    d: 'Based on Psalm 103 — a new day dawns and there are countless reasons to sing.' },
  { t: 'Blessed Be Your Name', a: 'Matt Redman', c: 'England', r: 'Europe', y: 2002, l: 'English', e: '🌞🌧️🙌', k: 'worship',
    d: 'A song about praising God in seasons of plenty and in the desert — echoing Job 1:21.' },
  { t: 'The Heart of Worship', a: 'Matt Redman', c: 'England', r: 'Europe', y: 1997, l: 'English', e: '❤️🎵🔙', k: 'worship',
    d: 'Written after a church stripped away its music to remember worship is all about Jesus.' },
  { t: 'Here I Am to Worship', a: 'Tim Hughes', c: 'England', r: 'Europe', y: 2000, l: 'English', e: '💡🙇‍♂️🙌', k: 'worship',
    d: 'A song to the Light of the world who stepped down into darkness.' },
  { t: 'Shine, Jesus, Shine', a: 'Graham Kendrick', c: 'England', r: 'Europe', y: 1987, l: 'English', e: '🔦✨🌍', k: 'worship', alt: ['Shine Jesus Shine'],
    d: 'A 1980s British chorus asking the Light of the World to fill the land.' },
  { t: 'The Servant King', a: 'Graham Kendrick', c: 'England', r: 'Europe', y: 1983, l: 'English', e: '👑🧎🦶', k: 'worship',
    d: 'A hymn about the King who came to serve — hands that flung stars into space, pierced by nails.' },
  { t: 'In Christ Alone', a: 'Keith Getty & Stuart Townend', c: 'Northern Ireland', r: 'Europe', y: 2001, l: 'English', e: '🪨✝️💡', k: 'hymn',
    d: 'A modern hymn telling the whole gospel story, from the cradle to the empty tomb.' },
  { t: 'Days of Elijah', a: 'Robin Mark', c: 'Northern Ireland', r: 'Europe', y: 1994, l: 'English', e: '🔥📯🐎', k: 'worship',
    d: 'A lively song packed with Old Testament images — Moses, David, Ezekiel and the year of Jubilee.' },
  { t: 'Be Thou My Vision', a: 'Traditional (Ireland)', c: 'Ireland', r: 'Europe', l: 'Irish / English', e: '👁️☘️🌅', k: 'hymn',
    d: 'An ancient Irish prayer set to the folk tune "Slane", asking God to be one\'s only vision.' },
  { t: 'Amazing Grace', a: 'John Newton', c: 'England', r: 'Europe', y: 1779, l: 'English', e: '⛓️🚢😲', k: 'hymn',
    d: 'Written by a former slave-ship captain turned pastor — once blind, now I see.' },
  { t: 'Rock of Ages', a: 'Augustus Toplady', c: 'England', r: 'Europe', y: 1776, l: 'English', e: '🪨⏳🙏', k: 'hymn',
    d: 'An 18th-century hymn about hiding in the cleft of the rock.' },
  { t: 'When I Survey the Wondrous Cross', a: 'Isaac Watts', c: 'England', r: 'Europe', y: 1707, l: 'English', e: '👀✝️👑', k: 'hymn',
    d: 'A meditation on the cross by the "father of English hymnody".' },
  { t: 'Joy to the World', a: 'Isaac Watts', c: 'England', r: 'Europe', y: 1719, l: 'English', e: '😃🌍👑', k: 'hymn',
    d: 'A paraphrase of Psalm 98, now one of the most sung Christmas carols.' },
  { t: 'O for a Thousand Tongues to Sing', a: 'Charles Wesley', c: 'England', r: 'Europe', y: 1739, l: 'English', e: '👅✖️1️⃣0️⃣0️⃣0️⃣', k: 'hymn',
    d: 'Written by a Methodist hymn-writer to celebrate the anniversary of his conversion.' },
  { t: 'Hark! The Herald Angels Sing', a: 'Charles Wesley', c: 'England', r: 'Europe', y: 1739, l: 'English', e: '📯😇👶', k: 'hymn', alt: ['Hark the Herald Angels Sing'],
    d: 'A Christmas carol later set to music by Felix Mendelssohn.' },
  { t: 'Abide with Me', a: 'Henry Francis Lyte', c: 'England', r: 'Europe', y: 1847, l: 'English', e: '🌇🕯️🙏', k: 'hymn',
    d: 'Written by a dying vicar as evening falls — famously sung before English cup finals.' },
  { t: 'Just As I Am', a: 'Charlotte Elliott', c: 'England', r: 'Europe', y: 1835, l: 'English', e: '🧍‍♀️🐑🙏', k: 'hymn',
    d: 'The hymn used at the end of countless Billy Graham crusades.' },
  { t: 'Nearer, My God, to Thee', a: 'Sarah Flower Adams', c: 'England', r: 'Europe', l: 'English', e: '🪜🚢🎻', k: 'hymn', alt: ['Nearer My God to Thee'],
    d: 'Inspired by Jacob\'s ladder — and remembered as the hymn played as the Titanic sank.' },
  { t: 'Onward, Christian Soldiers', a: 'Sabine Baring-Gould', c: 'England', r: 'Europe', y: 1865, l: 'English', e: '🚶‍♂️🛡️✝️', k: 'hymn', alt: ['Onward Christian Soldiers'],
    d: 'Written for a children\'s procession, later set to music by Arthur Sullivan.' },
  { t: 'Crown Him with Many Crowns', a: 'Matthew Bridges', c: 'England', r: 'Europe', y: 1851, l: 'English', e: '👑👑👑', k: 'hymn',
    d: 'A hymn inspired by Revelation 19:12, about the Lamb upon His throne.' },
  { t: 'A Mighty Fortress Is Our God', a: 'Martin Luther', c: 'Germany', r: 'Europe', y: 1529, l: 'German', e: '🏰🛡️📜', k: 'hymn', alt: ['Ein feste Burg'],
    d: 'The "battle hymn of the Reformation", based on Psalm 46.' },
  { t: 'Silent Night', a: 'Joseph Mohr & Franz Gruber', c: 'Austria', r: 'Europe', y: 1818, l: 'German', e: '🌙🤫👶', k: 'hymn', alt: ['Stille Nacht'],
    d: 'First performed with a guitar in a small Austrian church on Christmas Eve.' },
  { t: 'How Great Thou Art', a: 'Carl Boberg', c: 'Sweden', r: 'Europe', y: 1885, l: 'Swedish', e: '⛈️🌲🙌', k: 'hymn', alt: ['O Store Gud'],
    d: 'A Swedish poem written after a thunderstorm, later translated and sung by Elvis and Carrie Underwood.' },
  { t: 'O Holy Night', a: 'Adolphe Adam', c: 'France', r: 'Europe', y: 1847, l: 'French', e: '⭐🌃🧎', k: 'hymn', alt: ['Cantique de Noël', 'Minuit Chrétiens'],
    d: 'A French Christmas song — said to be one of the first melodies ever broadcast on radio.' },

  // ── Oceania ────────────────────────────────────────────────────
  { t: 'Oceans (Where Feet May Fail)', a: 'Hillsong United', c: 'Australia', r: 'Oceania', y: 2013, l: 'English', e: '🌊🦶🙏', k: 'worship', alt: ['Oceans'],
    d: 'A song about Jesus calling us out onto the waters, like Peter.' },
  { t: 'What a Beautiful Name', a: 'Hillsong Worship', c: 'Australia', r: 'Oceania', y: 2016, l: 'English', e: '📛✨✝️', k: 'worship',
    d: 'A Grammy-winning song that moves from beautiful, to wonderful, to powerful.' },
  { t: 'Shout to the Lord', a: 'Darlene Zschech', c: 'Australia', r: 'Oceania', y: 1994, l: 'English', e: '📣⛰️🌊', k: 'worship',
    d: 'The worship song that put an Australian church on the world map in the 1990s.' },
  { t: 'Mighty to Save', a: 'Hillsong Worship', c: 'Australia', r: 'Oceania', y: 2006, l: 'English', e: '💪🛟⛰️', k: 'worship',
    d: 'A declaration that the Saviour can move the mountains.' },
  { t: 'Cornerstone', a: 'Hillsong Worship', c: 'Australia', r: 'Oceania', y: 2012, l: 'English', e: '🧱📐⚓', k: 'worship',
    d: 'A modern reworking of the old hymn "The Solid Rock" with a new chorus.' },
  { t: 'Who You Say I Am', a: 'Hillsong Worship', c: 'Australia', r: 'Oceania', y: 2017, l: 'English', e: '🔓🪪👨‍👧', k: 'worship',
    d: 'A song about being free and chosen — a child of God.' },
  { t: 'King of Kings', a: 'Hillsong Worship', c: 'Australia', r: 'Oceania', y: 2019, l: 'English', e: '👑👑✝️', k: 'worship',
    d: 'A creed-like song tracing salvation history from the prophets to Pentecost.' },
  { t: 'Yet Not I but Through Christ in Me', a: 'CityAlight', c: 'Australia', r: 'Oceania', y: 2018, l: 'English', e: '🚫🙋➡️✝️', k: 'hymn', alt: ['Yet Not I'],
    d: 'A modern hymn from a Sydney church: what gift of grace is Jesus my Redeemer.' },

  // ── Latin America ──────────────────────────────────────────────
  { t: 'Renuévame', a: 'Marcos Witt', c: 'Mexico', r: 'Latin America', l: 'Spanish', e: '🔄❤️🙏', k: 'worship', alt: ['Renuevame'],
    d: 'A Spanish prayer asking God to renew me — by a Latin Grammy–winning worship leader.' },
  { t: 'Tu Fidelidad', a: 'Marcos Witt', c: 'Mexico', r: 'Latin America', l: 'Spanish', e: '🤝♾️🌎', k: 'worship',
    d: 'A Spanish song celebrating God\'s faithfulness that is great.' },
  { t: 'Ressuscita-me', a: 'Aline Barros', c: 'Brazil', r: 'Latin America', l: 'Portuguese', e: '⚰️➡️🌅🇧🇷', k: 'worship', alt: ['Ressuscitame', 'Ressuscita me'],
    d: 'A Portuguese song asking God to raise me up — inspired by Lazarus.' },

  // ── Traditional spirituals & choruses ──────────────────────────
  { t: 'Swing Low, Sweet Chariot', a: 'Traditional spiritual', c: 'USA', r: 'North America', l: 'English', e: '🎠🛞🏠', k: 'spiritual', alt: ['Swing Low Sweet Chariot', 'Swing Low'],
    d: 'An African-American spiritual about a chariot coming to carry me home, inspired by Elijah.' },
  { t: 'Go Tell It on the Mountain', a: 'Traditional spiritual', c: 'USA', r: 'North America', l: 'English', e: '📣⛰️👶', k: 'spiritual',
    d: 'A spiritual announcing the birth of Jesus over the hills and everywhere.' },
  { t: 'Were You There', a: 'Traditional spiritual', c: 'USA', r: 'North America', l: 'English', e: '❓✝️😢', k: 'spiritual',
    d: 'A spiritual that places the singer at the crucifixion and asks if you were there.' },
  { t: 'He\'s Got the Whole World in His Hands', a: 'Traditional spiritual', c: 'USA', r: 'North America', l: 'English', e: '🌍🤲👶', k: 'spiritual',
    alt: ['Whole World in His Hands', 'Hes Got the Whole World'], d: 'A spiritual about God holding everything — the wind, the rain, the little baby.' },
  { t: 'Kumbaya', a: 'Traditional spiritual', c: 'USA', r: 'North America', l: 'English / Gullah', e: '🔥🙏🎸', k: 'spiritual', alt: ['Kum ba yah', 'Come by here'],
    d: 'A Gullah spiritual asking the Lord to "come by here".' },
  { t: 'This Little Light of Mine', a: 'Traditional', c: 'USA', r: 'North America', l: 'English', e: '🕯️👧🌎', k: 'spiritual',
    d: 'A children\'s gospel chorus inspired by Matthew 5 — don\'t hide it under a bushel.' },
];
