// Bible trivia. [question, correct, [wrong answers], difficulty e|m|h]
export const TRIVIA = [
  // Beginnings
  ['On which day did God create the sun, moon and stars?', 'Day 4', ['Day 1', 'Day 3', 'Day 6'], 'm'],
  ['What did God create on the first day?', 'Light', ['Animals', 'Plants', 'The sea'], 'e'],
  ['What was the name of the garden where Adam and Eve lived?', 'Eden', ['Gethsemane', 'Goshen', 'Canaan'], 'e'],
  ['Which of Adam and Eve\'s sons was born after Abel\'s death?', 'Seth', ['Enoch', 'Enosh', 'Lamech'], 'm'],
  ['Who "walked with God" and was taken so that he did not see death?', 'Enoch', ['Methuselah', 'Lamech', 'Seth'], 'm'],
  ['How many of each clean animal did Noah take into the ark?', 'Seven pairs', ['One pair', 'Two pairs', 'Ten pairs'], 'h'],
  ['On which mountains did Noah\'s ark come to rest?', 'Ararat', ['Sinai', 'Carmel', 'Hermon'], 'e'],
  ['What sign did God give as a promise never to flood the earth again?', 'A rainbow', ['A dove', 'A star', 'An olive branch'], 'e'],
  ['Where did people try to build a tower reaching to heaven?', 'Babel', ['Jericho', 'Nineveh', 'Ur'], 'e'],
  ['What city did Abram leave when God called him?', 'Ur', ['Haran', 'Babylon', 'Damascus'], 'm'],
  ['What happened to Lot\'s wife when she looked back?', 'She became a pillar of salt', ['She went blind', 'She turned to stone', 'She fell asleep'], 'e'],
  ['What did Esau sell his birthright for?', 'A bowl of stew', ['Thirty silver coins', 'A goat', 'A coat'], 'e'],
  ['How many sons did Jacob have?', '12', ['10', '7', '14'], 'e'],
  ['Who was Joseph\'s youngest full brother?', 'Benjamin', ['Judah', 'Reuben', 'Levi'], 'm'],
  ['Whose wife falsely accused Joseph?', 'Potiphar\'s', ['Pharaoh\'s', 'Laban\'s', 'Judah\'s'], 'm'],

  // Exodus & wilderness
  ['Who found baby Moses in the river?', 'Pharaoh\'s daughter', ['Miriam', 'Jochebed', 'Zipporah'], 'e'],
  ['What was the first plague of Egypt?', 'Water turned to blood', ['Frogs', 'Locusts', 'Darkness'], 'e'],
  ['What was the last plague of Egypt?', 'Death of the firstborn', ['Darkness', 'Hail', 'Boils'], 'e'],
  ['How many plagues did God send on Egypt?', '10', ['7', '12', '40'], 'e'],
  ['What food did God send from heaven in the wilderness?', 'Manna', ['Figs', 'Barley loaves', 'Honey cakes'], 'e'],
  ['How many years did Israel wander in the wilderness?', '40', ['7', '12', '70'], 'e'],
  ['What did Moses strike to get water in the desert?', 'A rock', ['A tree', 'The sand', 'A well'], 'e'],
  ['What idol did the Israelites make at Mount Sinai?', 'A golden calf', ['A bronze snake', 'A silver bull', 'A stone lion'], 'e'],
  ['Who was Moses\' father-in-law?', 'Jethro', ['Laban', 'Aaron', 'Hur'], 'm'],
  ['What did Moses lift up on a pole so bitten people could live?', 'A bronze serpent', ['A golden lamb', 'His staff', 'A banner'], 'm'],
  ['Which two men held up Moses\' hands during the battle with Amalek?', 'Aaron and Hur', ['Joshua and Caleb', 'Eleazar and Ithamar', 'Nadab and Abihu'], 'h'],
  ['How many spies did Moses send into Canaan?', '12', ['2', '7', '40'], 'm'],
  ['What did the spies bring back from Canaan, carried on a pole?', 'A cluster of grapes', ['A lamb', 'A honeycomb', 'A giant\'s sword'], 'm'],

  // Conquest & judges
  ['How many times did Israel march around Jericho on the seventh day?', '7', ['1', '3', '12'], 'e'],
  ['Who replaced Moses as leader of Israel?', 'Joshua', ['Caleb', 'Aaron', 'Gideon'], 'e'],
  ['What river did Israel cross on dry ground to enter Canaan?', 'Jordan', ['Nile', 'Euphrates', 'Kidron'], 'e'],
  ['Which judge was left-handed and defeated King Eglon?', 'Ehud', ['Othniel', 'Jephthah', 'Shamgar'], 'h'],
  ['Which woman killed Sisera with a tent peg?', 'Jael', ['Deborah', 'Delilah', 'Rahab'], 'm'],
  ['How many men did Gideon take to fight the Midianites?', '300', ['3,000', '30', '12'], 'e'],
  ['What animal did Samson kill with his bare hands?', 'A lion', ['A bear', 'A wolf', 'A bull'], 'e'],
  ['What did Samson use to kill a thousand Philistines?', 'A donkey\'s jawbone', ['A sword', 'A pillar', 'A torch'], 'm'],

  // Kings
  ['Who was the first king of Israel?', 'Saul', ['David', 'Solomon', 'Samuel'], 'e'],
  ['What was David\'s job before he became king?', 'Shepherd', ['Carpenter', 'Fisherman', 'Soldier'], 'e'],
  ['How many stones did David pick up before facing Goliath?', '5', ['1', '3', '7'], 'm'],
  ['Who was David\'s father?', 'Jesse', ['Obed', 'Boaz', 'Kish'], 'm'],
  ['Which king asked God for wisdom?', 'Solomon', ['David', 'Hezekiah', 'Josiah'], 'e'],
  ['Who built the first temple in Jerusalem?', 'Solomon', ['David', 'Zerubbabel', 'Herod'], 'e'],
  ['After Solomon, the kingdom split. What was the southern kingdom called?', 'Judah', ['Israel', 'Samaria', 'Edom'], 'm'],
  ['Which prophet challenged 450 prophets of Baal?', 'Elijah', ['Elisha', 'Jeremiah', 'Nathan'], 'e'],
  ['What birds fed Elijah by the brook?', 'Ravens', ['Doves', 'Eagles', 'Sparrows'], 'e'],
  ['How did Elijah go up to heaven?', 'In a whirlwind', ['On a cloud', 'Up a ladder', 'Through a gate'], 'e'],
  ['Which king of Judah became king at seven years old?', 'Joash', ['Josiah', 'Uzziah', 'Manasseh'], 'h'],
  ['Which Babylonian king destroyed Jerusalem in 586 BC?', 'Nebuchadnezzar', ['Cyrus', 'Darius', 'Sennacherib'], 'm'],
  ['Which Persian king allowed the Jews to return and rebuild the temple?', 'Cyrus', ['Xerxes', 'Nebuchadnezzar', 'Belshazzar'], 'm'],
  ['Who threw Jeremiah into a cistern?', 'Officials of King Zedekiah', ['The Babylonians', 'Jezebel\'s guards', 'The Egyptians'], 'h'],

  // Prophets & exile
  ['Where was Jonah told to preach?', 'Nineveh', ['Babylon', 'Tarshish', 'Jerusalem'], 'e'],
  ['How long was Jonah inside the great fish?', 'Three days and three nights', ['Seven days', 'Forty days', 'One night'], 'e'],
  ['What did Daniel refuse to eat in Babylon?', 'The king\'s food and wine', ['Bread', 'Fish', 'Honey'], 'm'],
  ['What were Shadrach, Meshach and Abednego thrown into?', 'A fiery furnace', ['A lions\' den', 'A pit', 'The sea'], 'e'],
  ['Who interpreted the writing on the wall?', 'Daniel', ['Ezekiel', 'Joseph', 'Nehemiah'], 'e'],
  ['At whose feast did the writing on the wall appear?', 'Belshazzar', ['Nebuchadnezzar', 'Darius', 'Xerxes'], 'm'],
  ['Which prophet saw a valley of dry bones come to life?', 'Ezekiel', ['Isaiah', 'Daniel', 'Joel'], 'e'],
  ['Which prophet married Gomer?', 'Hosea', ['Amos', 'Micah', 'Joel'], 'm'],
  ['Which prophet was a shepherd and fig farmer from Tekoa?', 'Amos', ['Micah', 'Habakkuk', 'Obadiah'], 'h'],
  ['Who was the queen who saved her people from Haman\'s plot?', 'Esther', ['Vashti', 'Jezebel', 'Bathsheba'], 'e'],
  ['Which Jewish festival celebrates Esther\'s victory?', 'Purim', ['Passover', 'Hanukkah', 'Pentecost'], 'm'],
  ['Who rebuilt the walls of Jerusalem?', 'Nehemiah', ['Ezra', 'Zerubbabel', 'Haggai'], 'e'],
  ['Which prophet foretold that the Messiah would be born in Bethlehem?', 'Micah', ['Isaiah', 'Malachi', 'Zechariah'], 'm'],

  // Poetry & wisdom
  ['Which is the longest book of the Bible by chapters?', 'Psalms', ['Isaiah', 'Genesis', 'Jeremiah'], 'e'],
  ['Which is the longest chapter in the Bible?', 'Psalm 119', ['Psalm 23', 'Isaiah 53', 'Genesis 1'], 'm'],
  ['Which is the shortest verse in the English Bible (KJV)?', '"Jesus wept."', ['"Pray without ceasing."', '"Rejoice evermore."', '"God is love."'], 'e'],
  ['Which book describes the "virtuous woman" or "wife of noble character"?', 'Proverbs', ['Ruth', 'Esther', 'Song of Solomon'], 'm'],
  ['Which book says, "To every thing there is a season"?', 'Ecclesiastes', ['Proverbs', 'Psalms', 'Job'], 'm'],
  ['How many friends came to comfort Job at first?', '3', ['2', '4', '7'], 'm'],

  // Jesus' life
  ['In which town was Jesus born?', 'Bethlehem', ['Nazareth', 'Jerusalem', 'Capernaum'], 'e'],
  ['In which town did Jesus grow up?', 'Nazareth', ['Bethlehem', 'Bethany', 'Jericho'], 'e'],
  ['What gifts did the wise men bring?', 'Gold, frankincense and myrrh', ['Gold, silver and bronze', 'Bread, wine and oil', 'Spices, silk and jewels'], 'e'],
  ['Who baptized Jesus?', 'John the Baptist', ['Peter', 'Andrew', 'Nicodemus'], 'e'],
  ['How many days did Jesus fast in the wilderness?', '40', ['3', '7', '12'], 'e'],
  ['What was Jesus\' first recorded miracle?', 'Turning water into wine', ['Healing a blind man', 'Walking on water', 'Feeding the 5,000'], 'e'],
  ['In which town did Jesus turn water into wine?', 'Cana', ['Nain', 'Bethany', 'Capernaum'], 'm'],
  ['How many loaves and fish fed the 5,000?', '5 loaves and 2 fish', ['7 loaves and 3 fish', '2 loaves and 5 fish', '12 loaves and 2 fish'], 'e'],
  ['How many baskets of leftovers were collected after feeding the 5,000?', '12', ['7', '5', '3'], 'm'],
  ['What was the profession of Peter, Andrew, James and John?', 'Fishermen', ['Tax collectors', 'Carpenters', 'Tentmakers'], 'e'],
  ['On which mountain was Jesus transfigured (traditionally)?', 'Mount Tabor', ['Mount Sinai', 'Mount Carmel', 'Mount Ararat'], 'h'],
  ['Which two Old Testament figures appeared with Jesus at the Transfiguration?', 'Moses and Elijah', ['Abraham and David', 'Elijah and Elisha', 'Moses and Aaron'], 'm'],
  ['Where did Jesus pray before his arrest?', 'Gethsemane', ['Golgotha', 'Bethany', 'The temple'], 'e'],
  ['How many times did Peter deny Jesus?', '3', ['1', '2', '7'], 'e'],
  ['How much was Judas paid to betray Jesus?', '30 pieces of silver', ['20 pieces of silver', '40 shekels of gold', '100 denarii'], 'e'],
  ['Who was released instead of Jesus?', 'Barabbas', ['Barnabas', 'Bartimaeus', 'Malchus'], 'e'],
  ['Whose ear did Peter cut off in Gethsemane?', 'Malchus', ['Caiaphas', 'Annas', 'Barabbas'], 'm'],
  ['Who was high priest at Jesus\' trial?', 'Caiaphas', ['Annas', 'Eli', 'Zechariah'], 'm'],
  ['What does "Golgotha" mean?', 'Place of the skull', ['Garden of olives', 'House of bread', 'Valley of tears'], 'm'],
  ['On which day did Jesus rise from the dead?', 'The third day', ['The first day', 'The seventh day', 'The fortieth day'], 'e'],
  ['To which village were two disciples walking when the risen Jesus joined them?', 'Emmaus', ['Bethany', 'Jericho', 'Nain'], 'm'],
  ['How many days after his resurrection did Jesus ascend?', '40', ['3', '7', '50'], 'm'],
  ['In the parable, how many sheep did the shepherd leave to find the lost one?', '99', ['9', '49', '100'], 'e'],
  ['In the parable of the prodigal son, what animal was killed for the feast?', 'The fattened calf', ['A lamb', 'A goat', 'A dove'], 'e'],
  ['In the parable of the sower, what happened to seed on the path?', 'Birds ate it', ['It was choked by thorns', 'It withered in the sun', 'It grew a hundredfold'], 'm'],
  ['Who helped the injured man in Jesus\' famous parable?', 'A Samaritan', ['A priest', 'A Levite', 'A Roman soldier'], 'e'],
  ['How many lepers did Jesus heal when only one returned to say thank you?', '10', ['7', '12', '3'], 'e'],
  ['What did Jesus say is the greatest commandment?', 'Love the Lord your God with all your heart', ['Honour your father and mother', 'Do not steal', 'Keep the Sabbath'], 'e'],
  ['Which prayer begins "Our Father, which art in heaven"?', 'The Lord\'s Prayer', ['The Magnificat', 'The Nunc Dimittis', 'The Shema'], 'e'],
  ['How many Beatitudes are listed in Matthew 5?', '8 (or 9)', ['5', '10', '12'], 'h'],

  // Acts & church
  ['What happened on the day of Pentecost?', 'The Holy Spirit came upon the disciples', ['Jesus was born', 'The temple was destroyed', 'Paul was converted'], 'e'],
  ['Who replaced Judas as one of the Twelve?', 'Matthias', ['Barnabas', 'Stephen', 'Silas'], 'm'],
  ['Who was the first Christian martyr?', 'Stephen', ['James', 'Peter', 'Paul'], 'e'],
  ['Where was Paul going when he was blinded by a light?', 'Damascus', ['Jerusalem', 'Antioch', 'Rome'], 'e'],
  ['Who restored Paul\'s sight in Damascus?', 'Ananias', ['Barnabas', 'Peter', 'Silas'], 'm'],
  ['Where were believers first called "Christians"?', 'Antioch', ['Jerusalem', 'Rome', 'Corinth'], 'm'],
  ['What was Paul\'s trade?', 'Tentmaker', ['Fisherman', 'Physician', 'Carpenter'], 'e'],
  ['On which island was Paul shipwrecked?', 'Malta', ['Cyprus', 'Crete', 'Patmos'], 'm'],
  ['Which young man fell from a window while Paul preached late?', 'Eutychus', ['Timothy', 'Tychicus', 'Onesimus'], 'h'],
  ['Which couple lied about money and died in Acts 5?', 'Ananias and Sapphira', ['Aquila and Priscilla', 'Zechariah and Elizabeth', 'Felix and Drusilla'], 'm'],
  ['What was the name of the runaway slave Paul wrote about to Philemon?', 'Onesimus', ['Onesiphorus', 'Epaphras', 'Tychicus'], 'm'],
  ['Where was John when he received the Revelation?', 'Patmos', ['Ephesus', 'Rome', 'Malta'], 'e'],
  ['How many churches are addressed in Revelation 2–3?', '7', ['3', '10', '12'], 'e'],
  ['What is the last book of the Bible?', 'Revelation', ['Jude', 'Malachi', 'Acts'], 'e'],
  ['What is the first book of the New Testament?', 'Matthew', ['Mark', 'John', 'Acts'], 'e'],
  ['Which Gospel is the shortest?', 'Mark', ['Luke', 'John', 'Matthew'], 'm'],
  ['Which Gospel writer was a doctor?', 'Luke', ['Mark', 'Matthew', 'John'], 'e'],
  ['What is the "armour of God" item that is "the word of God"?', 'The sword of the Spirit', ['The shield of faith', 'The helmet of salvation', 'The belt of truth'], 'm'],
  ['How many books are in the Protestant Bible?', '66', ['73', '39', '27'], 'e'],
  ['How many books are in the Old Testament (Protestant)?', '39', ['27', '46', '66'], 'e'],
  ['How many books are in the New Testament?', '27', ['39', '21', '66'], 'e'],
  ['In which language was most of the Old Testament written?', 'Hebrew', ['Greek', 'Latin', 'Aramaic'], 'e'],
  ['In which language was the New Testament originally written?', 'Greek', ['Hebrew', 'Latin', 'Aramaic'], 'e'],

  // Africa & the Bible
  ['From which African city did Simon, who carried Jesus\' cross, come?', 'Cyrene', ['Alexandria', 'Carthage', 'Memphis'], 'm'],
  ['The official baptized by Philip served the queen of which people?', 'The Ethiopians', ['The Egyptians', 'The Libyans', 'The Sabeans'], 'e'],
  ['Which Ethiopian (Cushite) rescued Jeremiah from the cistern?', 'Ebed-Melech', ['Tirhakah', 'Zerah', 'Candace'], 'h'],
  ['Where did Joseph, Mary and Jesus flee to escape Herod?', 'Egypt', ['Ethiopia', 'Syria', 'Babylon'], 'e'],
  ['Which eloquent teacher in Acts came from Alexandria in Egypt?', 'Apollos', ['Aquila', 'Silas', 'Titus'], 'm'],
  ['Which Egyptian servant became the mother of Ishmael?', 'Hagar', ['Keturah', 'Zilpah', 'Asenath'], 'e'],
  ['What was the name of Joseph\'s Egyptian wife?', 'Asenath', ['Zipporah', 'Keturah', 'Tamar'], 'h'],
  ['Which river did the Pharaoh dream about seven cows coming up from?', 'The Nile', ['The Jordan', 'The Euphrates', 'The Tigris'], 'm'],
  ['Who from Cyrene is listed among the teachers at Antioch in Acts 13?', 'Lucius', ['Simeon', 'Manaen', 'Rufus'], 'h'],
];
