// Well-known verses (King James Version — public domain).
// [reference, text]
export const VERSES = [
  ['Genesis 1:1', 'In the beginning God created the heaven and the earth.'],
  ['Genesis 1:27', 'So God created man in his own image, in the image of God created he him; male and female created he them.'],
  ['Genesis 50:20', 'But as for you, ye thought evil against me; but God meant it unto good.'],
  ['Exodus 14:14', 'The LORD shall fight for you, and ye shall hold your peace.'],
  ['Exodus 20:3', 'Thou shalt have no other gods before me.'],
  ['Numbers 6:24', 'The LORD bless thee, and keep thee.'],
  ['Deuteronomy 6:5', 'And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.'],
  ['Deuteronomy 31:6', 'Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.'],
  ['Joshua 1:9', 'Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.'],
  ['Joshua 24:15', 'As for me and my house, we will serve the LORD.'],
  ['Ruth 1:16', 'Whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and thy God my God.'],
  ['1 Samuel 16:7', 'For man looketh on the outward appearance, but the LORD looketh on the heart.'],
  ['Nehemiah 8:10', 'For the joy of the LORD is your strength.'],
  ['Job 19:25', 'For I know that my redeemer liveth, and that he shall stand at the latter day upon the earth.'],
  ['Psalm 1:1', 'Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful.'],
  ['Psalm 19:1', 'The heavens declare the glory of God; and the firmament sheweth his handywork.'],
  ['Psalm 23:1', 'The LORD is my shepherd; I shall not want.'],
  ['Psalm 23:4', 'Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me.'],
  ['Psalm 27:1', 'The LORD is my light and my salvation; whom shall I fear?'],
  ['Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.'],
  ['Psalm 46:10', 'Be still, and know that I am God.'],
  ['Psalm 51:10', 'Create in me a clean heart, O God; and renew a right spirit within me.'],
  ['Psalm 91:1', 'He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.'],
  ['Psalm 100:4', 'Enter into his gates with thanksgiving, and into his courts with praise: be thankful unto him, and bless his name.'],
  ['Psalm 103:1', 'Bless the LORD, O my soul: and all that is within me, bless his holy name.'],
  ['Psalm 118:24', 'This is the day which the LORD hath made; we will rejoice and be glad in it.'],
  ['Psalm 119:105', 'Thy word is a lamp unto my feet, and a light unto my path.'],
  ['Psalm 121:1', 'I will lift up mine eyes unto the hills, from whence cometh my help.'],
  ['Psalm 133:1', 'Behold, how good and how pleasant it is for brethren to dwell together in unity!'],
  ['Psalm 139:14', 'I will praise thee; for I am fearfully and wonderfully made.'],
  ['Psalm 150:6', 'Let every thing that hath breath praise the LORD.'],
  ['Proverbs 3:5', 'Trust in the LORD with all thine heart; and lean not unto thine own understanding.'],
  ['Proverbs 3:6', 'In all thy ways acknowledge him, and he shall direct thy paths.'],
  ['Proverbs 15:1', 'A soft answer turneth away wrath: but grievous words stir up anger.'],
  ['Proverbs 18:10', 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe.'],
  ['Proverbs 22:6', 'Train up a child in the way he should go: and when he is old, he will not depart from it.'],
  ['Ecclesiastes 3:1', 'To every thing there is a season, and a time to every purpose under the heaven.'],
  ['Isaiah 9:6', 'For unto us a child is born, unto us a son is given: and the government shall be upon his shoulder.'],
  ['Isaiah 40:8', 'The grass withereth, the flower fadeth: but the word of our God shall stand for ever.'],
  ['Isaiah 40:31', 'But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles.'],
  ['Isaiah 41:10', 'Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee.'],
  ['Isaiah 53:5', 'But he was wounded for our transgressions, he was bruised for our iniquities.'],
  ['Isaiah 53:6', 'All we like sheep have gone astray; we have turned every one to his own way.'],
  ['Isaiah 6:8', 'Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I, Here am I; send me.'],
  ['Jeremiah 29:11', 'For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.'],
  ['Jeremiah 33:3', 'Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.'],
  ['Lamentations 3:23', 'They are new every morning: great is thy faithfulness.'],
  ['Micah 6:8', 'And what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?'],
  ['Habakkuk 2:4', 'But the just shall live by his faith.'],
  ['Zechariah 4:6', 'Not by might, nor by power, but by my spirit, saith the LORD of hosts.'],
  ['Malachi 3:10', 'Bring ye all the tithes into the storehouse, that there may be meat in mine house.'],
  ['Matthew 5:14', 'Ye are the light of the world. A city that is set on an hill cannot be hid.'],
  ['Matthew 5:9', 'Blessed are the peacemakers: for they shall be called the children of God.'],
  ['Matthew 6:33', 'But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.'],
  ['Matthew 7:7', 'Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.'],
  ['Matthew 11:28', 'Come unto me, all ye that labour and are heavy laden, and I will give you rest.'],
  ['Matthew 19:26', 'With men this is impossible; but with God all things are possible.'],
  ['Matthew 28:19', 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost.'],
  ['Mark 16:15', 'Go ye into all the world, and preach the gospel to every creature.'],
  ['Luke 1:37', 'For with God nothing shall be impossible.'],
  ['Luke 2:11', 'For unto you is born this day in the city of David a Saviour, which is Christ the Lord.'],
  ['Luke 6:31', 'And as ye would that men should do to you, do ye also to them likewise.'],
  ['John 1:1', 'In the beginning was the Word, and the Word was with God, and the Word was God.'],
  ['John 1:14', 'And the Word was made flesh, and dwelt among us.'],
  ['John 3:16', 'For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.'],
  ['John 8:32', 'And ye shall know the truth, and the truth shall make you free.'],
  ['John 10:11', 'I am the good shepherd: the good shepherd giveth his life for the sheep.'],
  ['John 11:25', 'I am the resurrection, and the life: he that believeth in me, though he were dead, yet shall he live.'],
  ['John 11:35', 'Jesus wept.'],
  ['John 13:34', 'A new commandment I give unto you, That ye love one another; as I have loved you.'],
  ['John 14:6', 'I am the way, the truth, and the life: no man cometh unto the Father, but by me.'],
  ['John 14:27', 'Peace I leave with you, my peace I give unto you.'],
  ['John 15:5', 'I am the vine, ye are the branches.'],
  ['John 16:33', 'In the world ye shall have tribulation: but be of good cheer; I have overcome the world.'],
  ['Acts 1:8', 'But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me.'],
  ['Acts 16:31', 'Believe on the Lord Jesus Christ, and thou shalt be saved, and thy house.'],
  ['Romans 3:23', 'For all have sinned, and come short of the glory of God.'],
  ['Romans 5:8', 'But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.'],
  ['Romans 6:23', 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.'],
  ['Romans 8:28', 'And we know that all things work together for good to them that love God.'],
  ['Romans 8:31', 'If God be for us, who can be against us?'],
  ['Romans 10:17', 'So then faith cometh by hearing, and hearing by the word of God.'],
  ['Romans 12:2', 'And be not conformed to this world: but be ye transformed by the renewing of your mind.'],
  ['Romans 12:12', 'Rejoicing in hope; patient in tribulation; continuing instant in prayer.'],
  ['1 Corinthians 10:31', 'Whether therefore ye eat, or drink, or whatsoever ye do, do all to the glory of God.'],
  ['1 Corinthians 13:4', 'Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up.'],
  ['1 Corinthians 13:13', 'And now abideth faith, hope, charity, these three; but the greatest of these is charity.'],
  ['2 Corinthians 5:17', 'Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.'],
  ['2 Corinthians 12:9', 'My grace is sufficient for thee: for my strength is made perfect in weakness.'],
  ['Galatians 5:22', 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith.'],
  ['Galatians 6:9', 'And let us not be weary in well doing: for in due season we shall reap, if we faint not.'],
  ['Ephesians 2:8', 'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God.'],
  ['Ephesians 4:32', 'And be ye kind one to another, tenderhearted, forgiving one another.'],
  ['Ephesians 6:11', 'Put on the whole armour of God, that ye may be able to stand against the wiles of the devil.'],
  ['Philippians 4:4', 'Rejoice in the Lord alway: and again I say, Rejoice.'],
  ['Philippians 4:6', 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.'],
  ['Philippians 4:13', 'I can do all things through Christ which strengtheneth me.'],
  ['Philippians 4:19', 'But my God shall supply all your need according to his riches in glory by Christ Jesus.'],
  ['Colossians 3:23', 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men.'],
  ['1 Thessalonians 5:16', 'Rejoice evermore.'],
  ['1 Thessalonians 5:17', 'Pray without ceasing.'],
  ['1 Thessalonians 5:18', 'In every thing give thanks: for this is the will of God in Christ Jesus concerning you.'],
  ['2 Timothy 1:7', 'For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.'],
  ['2 Timothy 3:16', 'All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.'],
  ['Hebrews 11:1', 'Now faith is the substance of things hoped for, the evidence of things not seen.'],
  ['Hebrews 12:2', 'Looking unto Jesus the author and finisher of our faith.'],
  ['Hebrews 13:8', 'Jesus Christ the same yesterday, and to day, and for ever.'],
  ['James 1:22', 'But be ye doers of the word, and not hearers only, deceiving your own selves.'],
  ['James 4:8', 'Draw nigh to God, and he will draw nigh to you.'],
  ['1 Peter 5:7', 'Casting all your care upon him; for he careth for you.'],
  ['1 John 1:9', 'If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.'],
  ['1 John 4:8', 'He that loveth not knoweth not God; for God is love.'],
  ['1 John 4:19', 'We love him, because he first loved us.'],
  ['Revelation 3:20', 'Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him.'],
  ['Revelation 21:4', 'And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying.'],
  ['Revelation 22:13', 'I am Alpha and Omega, the beginning and the end, the first and the last.'],
];

// "Who said it?" — [quote (KJV), speaker, context]
export const QUOTES = [
  ['Am I my brother\'s keeper?', 'Cain', 'Genesis 4:9'],
  ['God will provide himself a lamb.', 'Abraham', 'Genesis 22:8'],
  ['Shall not the Judge of all the earth do right?', 'Abraham', 'Genesis 18:25'],
  ['I will not let thee go, except thou bless me.', 'Jacob', 'Genesis 32:26'],
  ['Ye thought evil against me; but God meant it unto good.', 'Joseph', 'Genesis 50:20'],
  ['Who am I, that I should go unto Pharaoh?', 'Moses', 'Exodus 3:11'],
  ['Sing ye to the LORD, for he hath triumphed gloriously.', 'Miriam', 'Exodus 15:21'],
  ['As for me and my house, we will serve the LORD.', 'Joshua', 'Joshua 24:15'],
  ['If thou wilt go with me, then I will go.', 'Barak', 'Judges 4:8'],
  ['Whither thou goest, I will go.', 'Ruth', 'Ruth 1:16'],
  ['Call me not Naomi, call me Mara.', 'Naomi', 'Ruth 1:20'],
  ['Speak; for thy servant heareth.', 'Samuel', '1 Samuel 3:10'],
  ['Is there not a cause?', 'David', '1 Samuel 17:29'],
  ['Who is this uncircumcised Philistine?', 'David', '1 Samuel 17:26'],
  ['Thou art the man.', 'Nathan', '2 Samuel 12:7'],
  ['Give therefore thy servant an understanding heart.', 'Solomon', '1 Kings 3:9'],
  ['How long halt ye between two opinions?', 'Elijah', '1 Kings 18:21'],
  ['Let a double portion of thy spirit be upon me.', 'Elisha', '2 Kings 2:9'],
  ['If I perish, I perish.', 'Esther', 'Esther 4:16'],
  ['Who knoweth whether thou art come to the kingdom for such a time as this?', 'Mordecai', 'Esther 4:14'],
  ['The LORD gave, and the LORD hath taken away.', 'Job', 'Job 1:21'],
  ['Vanity of vanities; all is vanity.', 'Solomon', 'Ecclesiastes 1:2'],
  ['Here am I; send me.', 'Isaiah', 'Isaiah 6:8'],
  ['Ah, Lord GOD! behold, I cannot speak: for I am a child.', 'Jeremiah', 'Jeremiah 1:6'],
  ['Our God whom we serve is able to deliver us from the burning fiery furnace.', 'Shadrach, Meshach & Abednego', 'Daniel 3:17'],
  ['My God hath sent his angel, and hath shut the lions\' mouths.', 'Daniel', 'Daniel 6:22'],
  ['Salvation is of the LORD.', 'Jonah', 'Jonah 2:9'],
  ['Behold the handmaid of the Lord.', 'Mary, mother of Jesus', 'Luke 1:38'],
  ['My soul doth magnify the Lord.', 'Mary, mother of Jesus', 'Luke 1:46'],
  ['Lord, now lettest thou thy servant depart in peace.', 'Simeon', 'Luke 2:29'],
  ['Behold the Lamb of God, which taketh away the sin of the world.', 'John the Baptist', 'John 1:29'],
  ['He must increase, but I must decrease.', 'John the Baptist', 'John 3:30'],
  ['Can there any good thing come out of Nazareth?', 'Nathanael', 'John 1:46'],
  ['How can a man be born when he is old?', 'Nicodemus', 'John 3:4'],
  ['Sir, give me this water, that I thirst not.', 'The Samaritan woman', 'John 4:15'],
  ['Thou art the Christ, the Son of the living God.', 'Peter', 'Matthew 16:16'],
  ['Silver and gold have I none; but such as I have give I thee.', 'Peter', 'Acts 3:6'],
  ['Master, we have toiled all the night, and have taken nothing.', 'Peter', 'Luke 5:5'],
  ['My Lord and my God.', 'Thomas', 'John 20:28'],
  ['Lord, I am not worthy that thou shouldest come under my roof.', 'A Roman centurion', 'Matthew 8:8'],
  ['Truly this was the Son of God.', 'A Roman centurion', 'Matthew 27:54'],
  ['Lord, remember me when thou comest into thy kingdom.', 'The thief on the cross', 'Luke 23:42'],
  ['What is truth?', 'Pontius Pilate', 'John 18:38'],
  ['What I have written I have written.', 'Pontius Pilate', 'John 19:22'],
  ['Behold, Lord, the half of my goods I give to the poor.', 'Zacchaeus', 'Luke 19:8'],
  ['Lord, dost thou not care that my sister hath left me to serve alone?', 'Martha', 'Luke 10:40'],
  ['Lord, lay not this sin to their charge.', 'Stephen', 'Acts 7:60'],
  ['Understandest thou what thou readest?', 'Philip the Evangelist', 'Acts 8:30'],
  ['Sirs, what must I do to be saved?', 'The Philippian jailer', 'Acts 16:30'],
  ['Almost thou persuadest me to be a Christian.', 'King Agrippa', 'Acts 26:28'],
  ['I have fought a good fight, I have finished my course, I have kept the faith.', 'Paul', '2 Timothy 4:7'],
  ['For to me to live is Christ, and to die is gain.', 'Paul', 'Philippians 1:21'],
  ['Who art thou, Lord?', 'Paul', 'Acts 9:5'],
  ['Sirs, we would see Jesus.', 'Some Greeks at the feast', 'John 12:21'],
  ['Hath God said, Ye shall not eat of every tree of the garden?', 'The serpent', 'Genesis 3:1'],
  ['The woman whom thou gavest to be with me, she gave me of the tree.', 'Adam', 'Genesis 3:12'],
  ['Let my people go.', 'Moses', 'Exodus 5:1'],
];
